$axure.loadCurrentPage({
  "url":"支付.html",
  "generationDate":new Date(1463988217859.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a72075604c02482eafe4b1ebc6cdab09",
    "type":"Axure:Page",
    "name":"支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"db013f48512240d6a831e6c4a784f755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"608fcd041f2f440e9a291117f3b9b34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"3137eb9d070c4ba482d9164f06dd22b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa8e2ce405342c2954076dc88a73b09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"73c25b95407e4a35ad9402b7ecd6e30f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3035feb8531b4a56af6dcc917c67cbf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"e4cade7a5653437b9a5f8cfa9770c654",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "location":{
              "x":20,
              "y":419},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f72c409efb4b4795470c21ad220108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "location":{
                  "x":20,
                  "y":419},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付成功",
                      "target":{
                        "targetType":"page",
                        "url":"支付成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付/u6.png",
            "mouseOver~":"images/支付/u6.png"}},
{
          "id":"d53c3d94fd0443409f20bd546f8631e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0432fb6a90e940ae9466f4d427da2faa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 确认订单",
                      "target":{
                        "targetType":"page",
                        "url":"确认订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"64bc702b85cc4e398208e7e47cf18fba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":91},
            "size":{
              "width":360,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7326be58eb46428d5544174f1959d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":91},
                "size":{
                  "width":360,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付/u10.png"}},
{
          "id":"5be6079172664bcc857cfdc2acc041fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":108},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fde0431c3bd4647a52344b097c396c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":108},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"926eb473cec249e9a37e732037b43414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":10,
              "y":135},
            "size":{
              "width":339,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d2a7da8dbd0419fa19a91b0ecb22760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":10,
                  "y":135},
                "size":{
                  "width":339,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b544fedc4fe34459a39b5084d597f278",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":191},
            "size":{
              "width":360,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f30ebd0adfcc442e8e3592fff6f61686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":191},
                "size":{
                  "width":360,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付/u16.png"}},
{
          "id":"7bc9fb889b664e33bbd5d57e76ad2de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":199},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a34350d6e7402982485be7524cd911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":199},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd954b640d724caf90dec177d616265a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":228},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfa46913474b42e199c5d194fb8b9ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":228},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aff5bce348744b79ac665917c479050d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":360,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471b705a57b14aa7b4646dcdf577e554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":360,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付/u22.png"}},
{
          "id":"b72cc7c7c20647f787dfff6615847165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26714c7666ff498ba9ff8a6c942d1dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"213da17d3525445f85386c094d7e1780",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":301},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd17949af2c4dad9f2037fbce373d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":301},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4ea6c09e02d54ee488202bb8a493453f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":327},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ae062969a34ac3b4c8a79ef99a9e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":327},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "db013f48512240d6a831e6c4a784f755":{
      "scriptId":"u0"},
    "608fcd041f2f440e9a291117f3b9b34d":{
      "scriptId":"u1"},
    "3137eb9d070c4ba482d9164f06dd22b2":{
      "scriptId":"u2"},
    "0aa8e2ce405342c2954076dc88a73b09":{
      "scriptId":"u3"},
    "73c25b95407e4a35ad9402b7ecd6e30f":{
      "scriptId":"u4"},
    "3035feb8531b4a56af6dcc917c67cbf6":{
      "scriptId":"u5"},
    "e4cade7a5653437b9a5f8cfa9770c654":{
      "scriptId":"u6"},
    "67f72c409efb4b4795470c21ad220108":{
      "scriptId":"u7"},
    "d53c3d94fd0443409f20bd546f8631e9":{
      "scriptId":"u8"},
    "0432fb6a90e940ae9466f4d427da2faa":{
      "scriptId":"u9"},
    "64bc702b85cc4e398208e7e47cf18fba":{
      "scriptId":"u10"},
    "da7326be58eb46428d5544174f1959d0":{
      "scriptId":"u11"},
    "5be6079172664bcc857cfdc2acc041fb":{
      "scriptId":"u12"},
    "0fde0431c3bd4647a52344b097c396c9":{
      "scriptId":"u13"},
    "926eb473cec249e9a37e732037b43414":{
      "scriptId":"u14"},
    "5d2a7da8dbd0419fa19a91b0ecb22760":{
      "scriptId":"u15"},
    "b544fedc4fe34459a39b5084d597f278":{
      "scriptId":"u16"},
    "f30ebd0adfcc442e8e3592fff6f61686":{
      "scriptId":"u17"},
    "7bc9fb889b664e33bbd5d57e76ad2de6":{
      "scriptId":"u18"},
    "30a34350d6e7402982485be7524cd911":{
      "scriptId":"u19"},
    "bd954b640d724caf90dec177d616265a":{
      "scriptId":"u20"},
    "cfa46913474b42e199c5d194fb8b9ea4":{
      "scriptId":"u21"},
    "aff5bce348744b79ac665917c479050d":{
      "scriptId":"u22"},
    "471b705a57b14aa7b4646dcdf577e554":{
      "scriptId":"u23"},
    "b72cc7c7c20647f787dfff6615847165":{
      "scriptId":"u24"},
    "26714c7666ff498ba9ff8a6c942d1dbd":{
      "scriptId":"u25"},
    "213da17d3525445f85386c094d7e1780":{
      "scriptId":"u26"},
    "ccd17949af2c4dad9f2037fbce373d61":{
      "scriptId":"u27"},
    "4ea6c09e02d54ee488202bb8a493453f":{
      "scriptId":"u28"},
    "a9ae062969a34ac3b4c8a79ef99a9e05":{
      "scriptId":"u29"}}});