$axure.loadCurrentPage({
  "url":"个人中心_-未登录.html",
  "generationDate":new Date(1463988220615.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b1e315f993d41f9b5c15343f541b19d",
    "type":"Axure:Page",
    "name":"个人中心 -未登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4395f07465ca49a38f762e1db66e10bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da1aeead50ca4340a1120e333fe1ecb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"f5e70c71f7814b00b92df8bfaee55d97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e889a435c78406a8e33fa59050fe58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"fdc074973c514a1ab7f2a2c2a385ca85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"452f0e199b8b492c8c1558c3e146fc29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"730f8f59ebf446a495326ecb8f482907",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":91},
            "size":{
              "width":360,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b929af0b36c1424282c667db20a61271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":91},
                "size":{
                  "width":360,
                  "height":79},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心_-未登录/u6.png"}},
{
          "id":"085bf37cd6ec4e619b068df0e8a453a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":187},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35ba5511883641249fe431c64e0c00e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":187},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"613082ddabba4093864cbe972c6034da",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":20,
              "y":221},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"248749f9ef034735ab93b51a7849acb6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":20,
              "y":279},
            "size":{
              "width":180,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"26218fc0f6484a3683b1837929fa8f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":210,
              "y":279},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95e9bf3fa7a434aa52c65124bab456d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":210,
                  "y":279},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心_-未登录/u12.png"}},
{
          "id":"82c7b32ecd104528a430c6fbc4113360",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "location":{
              "x":20,
              "y":379},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd418dfa04349b4a695153784374c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "location":{
                  "x":20,
                  "y":379},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心 - 登录",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心_-_登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付/u6.png",
            "mouseOver~":"images/支付/u6.png"}},
{
          "id":"0afbb15383b742c0b68f0d826a61effc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":20,
              "y":425},
            "size":{
              "width":217,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45eada01146644e9940fb8998f1fba0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":20,
                  "y":425},
                "size":{
                  "width":217,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"839a17abe03e455799629e56c7131db8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":114,
              "y":124},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67f2960529c410caa90a165b276c3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":124},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae0a71f19a0b4870a9a1cf66a65ce430",
          "label":"tab条",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":445},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7edae1d178b7410dbb432bd10e9853d1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a9f3310ce24144c3b0758b5f5c0f678f",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae0f089264244f64941f11d3147cd663",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 tab条 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["ae0a71f19a0b4870a9a1cf66a65ce430"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u55.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0fd26b77819742f2acf315d424deb1b5",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9d80af03e28746a7b44e1d0bcdfe6b63",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":177},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a2f318c0d0b4dc2bbe910933a0527f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":177},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u57.png"}},
{
                  "id":"8147e1d5c277449b82ea22d55380c2d0",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":16},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e7a9aa6b2b145c89324b6bb07354ad4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":16},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u59.png"}},
{
                  "id":"fafd3ee06a9448ff883a04ee762815e8",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":19,
                      "y":43},
                    "size":{
                      "width":25,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e513f14945314048ab0a31c0e6700b8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":19,
                          "y":43},
                        "size":{
                          "width":25,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3aaa8db9dc8747ea9d0c74722fc9e03e",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":73},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14ae0903a1294882b7ade5047aefcb0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":73},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 购物车",
                              "target":{
                                "targetType":"page",
                                "url":"购物车.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u63.png"}},
{
                  "id":"d472814913a34c1caa73f68d40e1e120",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":66,
                      "y":99},
                    "size":{
                      "width":37,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bb517fc07ab458eabcaa78b1a2368dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":66,
                          "y":99},
                        "size":{
                          "width":37,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6a3656f758f449b3b595c91f92fc417b",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":118},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8c44b41b03f4ed1a8454c85045cfc11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":118},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"未登录",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心 -未登录",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心_-未登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"登录",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心 - 登录",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心_-_登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u67.png"}},
{
                  "id":"843b578f7ffe444bbd6fc3cb9e45b0bf",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":7,
                      "y":144},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"968db7f91d5747b7901a8c64881aaa86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":7,
                          "y":144},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a9df51aa795f43878e01d6c316525284",
                  "label":"",
                  "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "location":{
                      "x":16,
                      "y":67},
                    "size":{
                      "width":22,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"90c1331f35dc4fb7978cd5deab160636",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae0a71f19a0b4870a9a1cf66a65ce430",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "location":{
                          "x":16,
                          "y":67},
                        "size":{
                          "width":22,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 tab条 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["ae0a71f19a0b4870a9a1cf66a65ce430"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"74f1af5ca35f476db7f23bbe7f9be127",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":33,
              "y":102},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3c0b6f43f1a45c0b89906cd38bbfcec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":33,
                  "y":102},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心_-未登录/u39.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4395f07465ca49a38f762e1db66e10bc":{
      "scriptId":"u0"},
    "da1aeead50ca4340a1120e333fe1ecb4":{
      "scriptId":"u1"},
    "f5e70c71f7814b00b92df8bfaee55d97":{
      "scriptId":"u2"},
    "9e889a435c78406a8e33fa59050fe58c":{
      "scriptId":"u3"},
    "fdc074973c514a1ab7f2a2c2a385ca85":{
      "scriptId":"u4"},
    "452f0e199b8b492c8c1558c3e146fc29":{
      "scriptId":"u5"},
    "730f8f59ebf446a495326ecb8f482907":{
      "scriptId":"u6"},
    "b929af0b36c1424282c667db20a61271":{
      "scriptId":"u7"},
    "085bf37cd6ec4e619b068df0e8a453a8":{
      "scriptId":"u8"},
    "35ba5511883641249fe431c64e0c00e9":{
      "scriptId":"u9"},
    "613082ddabba4093864cbe972c6034da":{
      "scriptId":"u10"},
    "248749f9ef034735ab93b51a7849acb6":{
      "scriptId":"u11"},
    "26218fc0f6484a3683b1837929fa8f49":{
      "scriptId":"u12"},
    "a95e9bf3fa7a434aa52c65124bab456d":{
      "scriptId":"u13"},
    "82c7b32ecd104528a430c6fbc4113360":{
      "scriptId":"u14"},
    "4fd418dfa04349b4a695153784374c05":{
      "scriptId":"u15"},
    "0afbb15383b742c0b68f0d826a61effc":{
      "scriptId":"u16"},
    "45eada01146644e9940fb8998f1fba0a":{
      "scriptId":"u17"},
    "839a17abe03e455799629e56c7131db8":{
      "scriptId":"u18"},
    "e67f2960529c410caa90a165b276c3d3":{
      "scriptId":"u19"},
    "ae0a71f19a0b4870a9a1cf66a65ce430":{
      "scriptId":"u20"},
    "a9f3310ce24144c3b0758b5f5c0f678f":{
      "scriptId":"u21"},
    "ae0f089264244f64941f11d3147cd663":{
      "scriptId":"u22"},
    "9d80af03e28746a7b44e1d0bcdfe6b63":{
      "scriptId":"u23"},
    "8a2f318c0d0b4dc2bbe910933a0527f4":{
      "scriptId":"u24"},
    "8147e1d5c277449b82ea22d55380c2d0":{
      "scriptId":"u25"},
    "7e7a9aa6b2b145c89324b6bb07354ad4":{
      "scriptId":"u26"},
    "fafd3ee06a9448ff883a04ee762815e8":{
      "scriptId":"u27"},
    "e513f14945314048ab0a31c0e6700b8e":{
      "scriptId":"u28"},
    "3aaa8db9dc8747ea9d0c74722fc9e03e":{
      "scriptId":"u29"},
    "14ae0903a1294882b7ade5047aefcb0c":{
      "scriptId":"u30"},
    "d472814913a34c1caa73f68d40e1e120":{
      "scriptId":"u31"},
    "5bb517fc07ab458eabcaa78b1a2368dd":{
      "scriptId":"u32"},
    "6a3656f758f449b3b595c91f92fc417b":{
      "scriptId":"u33"},
    "a8c44b41b03f4ed1a8454c85045cfc11":{
      "scriptId":"u34"},
    "843b578f7ffe444bbd6fc3cb9e45b0bf":{
      "scriptId":"u35"},
    "968db7f91d5747b7901a8c64881aaa86":{
      "scriptId":"u36"},
    "a9df51aa795f43878e01d6c316525284":{
      "scriptId":"u37"},
    "90c1331f35dc4fb7978cd5deab160636":{
      "scriptId":"u38"},
    "74f1af5ca35f476db7f23bbe7f9be127":{
      "scriptId":"u39"},
    "e3c0b6f43f1a45c0b89906cd38bbfcec":{
      "scriptId":"u40"}}});