$axure.loadCurrentPage({
  "url":"商品_-_未支付.html",
  "generationDate":new Date(1463988223498.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"abc1d2ad94b843378cb4c17b4567d891",
    "type":"Axure:Page",
    "name":"商品 - 未支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd4f829cdee841a798511d8ffe6b6682",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed97715bb6b48b2ad554af1d44e4f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"0bc1d8c0982e4f61a52f9fc74c93b112",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49f6b9cb974145f281d938e85feb2e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"c382198e7edd4e26924b855e2d4d3b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39bb7ba6b1734e7791166ab27b808ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"a992361e979a47e1a00a9256a8cb99e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6504b9ac2b3845b584e79f8fe6a34bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"da1080436b11426fb530475acf118b61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":143},
            "size":{
              "width":360,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d533b3b747ef4abd87ae46c19c083c77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":143},
                "size":{
                  "width":360,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付_1/u20.png"}},
{
          "id":"6394edc2f76e4c24bc7fb7bc944b25d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":20,
              "y":158},
            "size":{
              "width":180,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b719966087e24e2a98fc46072cbe8d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":20,
                  "y":158},
                "size":{
                  "width":180,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"004b25463810444fba4dbedce7988309",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":20,
              "y":180},
            "size":{
              "width":330,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8c8f04c18ce4f13b6e5aca38e8c778e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":20,
                  "y":180},
                "size":{
                  "width":330,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95413cdfab584c83b138c326b9f4ff74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":237},
            "size":{
              "width":360,
              "height":235},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da141666939340299223e82b7d856dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":237},
                "size":{
                  "width":360,
                  "height":235},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品_-_已支付/u114.png"}},
{
          "id":"7f934070eaef44fa8ccaf2ea49d07b14",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":274},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"1b02e3f996ab45cca2e144fbe0b16aeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":251},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be045996bd3d435ab04977f96dc3fea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":251},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95a0c91df6c54142b42e6e64ced5256b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":288},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f87d8c1862844689bfb4069631f679e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":288},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u19.png"}},
{
          "id":"706abd30665040e58862a6f1825e46c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":73,
              "y":292},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d00789ecab347f5a590503a9a057a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":73,
                  "y":292},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4005f4a6d86b427ba662c20abe3a4872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":73,
              "y":310},
            "size":{
              "width":109,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a50163171904dc1a219c6941f4910c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":310},
                "size":{
                  "width":109,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c92451cac32d459b99fa9900121bbd17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":342},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"1dcf2ee2de7842f48999655d5c35d448",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":292},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c2cc1073cad46459b94bf2ffa52555e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":292},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6d266afa0c4a1e99e22a8707b5e1b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":435},
            "size":{
              "width":154,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48af5896cbdd43e79cc07cff8b03255b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":435},
                "size":{
                  "width":154,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"917dcd7390884b37aa1b271a339634d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":326},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"322167e6027449ac8d45d42bff2214ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":326},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45b003454fb14668a6aee020ca209b08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":358},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab59dcbcd62409dbf68f6c05f476c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":358},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u19.png"}},
{
          "id":"d0746ad34aaf47b49ea336d24434176a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":73,
              "y":362},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38c152492e94b058047014d0e6c9078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":73,
                  "y":362},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70e1dab78bbe46938cd38fac57aeb9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":73,
              "y":380},
            "size":{
              "width":109,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"191cc26884034132b8e48584ede458ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":380},
                "size":{
                  "width":109,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3032e6b7cb234ee38a08c3b9c0379530",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":412},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"a2bfabf0c03b4e14850664112cc3c4b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":362},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21aa0e606b6421483e4d785b2934d30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":362},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6ef40bb7d44623aafe3c715363defe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":396},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd6060136ec1426d957a7dabaedbf539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":396},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c24a937c1084a55bb2df29f58ea4132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":98},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9e67a12e91402ea5523a331d933701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":98},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7375eae01404999b331a2e51767a67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":19,
              "y":120},
            "size":{
              "width":212,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0702e119b6dc44deaee489f432b5f53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":19,
                  "y":120},
                "size":{
                  "width":212,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e570ea48c77942ebb90858186cbb010a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":526},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0752c8327f14852a7c5492906a7fddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":526},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"9d6e72cdbd604b619e63db2c12b3187d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":542},
            "size":{
              "width":180,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba38a2227b9f48c48c4b7b860a3845bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":542},
                "size":{
                  "width":180,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe3699370f7c4076a9f4c5f6854db11b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":537},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17deed3c3cd642288c693d4a00248dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":537},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_已支付/u46.png"}},
{
          "id":"4aea7836fe464d3493d63b7014b4c9c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":590},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b78f577017bf4ae7a54658ee69c7e55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":590},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u28.png"}},
{
          "id":"ffcb4a315997478aa5cf5773d2376ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":15,
              "y":607},
            "size":{
              "width":169,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a59226eaa3c0489db61ecfc67a6f85d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":15,
                  "y":607},
                "size":{
                  "width":169,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c6f7f9d4d234e23b3c9f0286cc87606",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":270,
              "y":598},
            "size":{
              "width":81,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"759b211fd6404f5994fd459a5eb536fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":270,
                  "y":598},
                "size":{
                  "width":81,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付",
                      "target":{
                        "targetType":"page",
                        "url":"支付_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认订单/u32.png"}},
{
          "id":"dd1f00af6ec64e249773f7572a72ef4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":269,
              "y":246},
            "size":{
              "width":81,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a861b20d62074d71b2ba30687ae0536b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":269,
                  "y":246},
                "size":{
                  "width":81,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_未支付/u40.png"}},
{
          "id":"d6439999dbfb45e899f7865b716dec21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":246},
            "size":{
              "width":240,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaf4f048d4084f74970c58947807293f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":246},
                "size":{
                  "width":240,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_未支付/u48.png"}},
{
          "id":"f718256fb979403099244bec933ed3ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":270},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c70f1e048f43668c1d97ea48ff6ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":270},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2381672c63fa4b95bd282d267edb98c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":304},
            "size":{
              "width":240,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/卡券_-_未支付/u52_line.png"}},
{
          "id":"f131a0b606ad40d39ad1420aa0ac0eca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":320},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"194579d07d924aa4bb426700b462259c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":320},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecb6fa4a1860427282e3684b517fe317",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":320},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cdea9838b394bd3bd5bfd8c23abc933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":320},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"813e59856a48467a9b68e27cbf527b56",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":250},
            "size":{
              "width":70,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/卡券详情/u85_end.png",
            "line~":"images/商品_-_未支付/u70_line.png"}},
{
          "id":"6c94d75f6c454b13a92200b3db664510",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":545},
            "size":{
              "width":50,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/卡券详情/u85_end.png",
            "line~":"images/卡券_-_已支付/u84_line.png"}},
{
          "id":"10a21b8c1ec44be8a9875026c85342e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":391,
              "y":541},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5d400e5598344eb83a429ad89ec8e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":391,
                  "y":541},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87d1db7f00e340c8b158183089d650f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":477},
            "size":{
              "width":360,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56397ded24a04920a6d0e87dfe40f6e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":477},
                "size":{
                  "width":360,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单（发票模块流程）/u94.png"}},
{
          "id":"bfc745d78fe24636b8a578c98649836d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":491},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13aad8db36264b2ba758b97aefd0a6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":491},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "bd4f829cdee841a798511d8ffe6b6682":{
      "scriptId":"u0"},
    "eed97715bb6b48b2ad554af1d44e4f0d":{
      "scriptId":"u1"},
    "0bc1d8c0982e4f61a52f9fc74c93b112":{
      "scriptId":"u2"},
    "49f6b9cb974145f281d938e85feb2e1a":{
      "scriptId":"u3"},
    "c382198e7edd4e26924b855e2d4d3b92":{
      "scriptId":"u4"},
    "39bb7ba6b1734e7791166ab27b808ec9":{
      "scriptId":"u5"},
    "a992361e979a47e1a00a9256a8cb99e6":{
      "scriptId":"u6"},
    "6504b9ac2b3845b584e79f8fe6a34bb8":{
      "scriptId":"u7"},
    "da1080436b11426fb530475acf118b61":{
      "scriptId":"u8"},
    "d533b3b747ef4abd87ae46c19c083c77":{
      "scriptId":"u9"},
    "6394edc2f76e4c24bc7fb7bc944b25d4":{
      "scriptId":"u10"},
    "b719966087e24e2a98fc46072cbe8d35":{
      "scriptId":"u11"},
    "004b25463810444fba4dbedce7988309":{
      "scriptId":"u12"},
    "c8c8f04c18ce4f13b6e5aca38e8c778e":{
      "scriptId":"u13"},
    "95413cdfab584c83b138c326b9f4ff74":{
      "scriptId":"u14"},
    "da141666939340299223e82b7d856dac":{
      "scriptId":"u15"},
    "7f934070eaef44fa8ccaf2ea49d07b14":{
      "scriptId":"u16"},
    "1b02e3f996ab45cca2e144fbe0b16aeb":{
      "scriptId":"u17"},
    "be045996bd3d435ab04977f96dc3fea1":{
      "scriptId":"u18"},
    "95a0c91df6c54142b42e6e64ced5256b":{
      "scriptId":"u19"},
    "5f87d8c1862844689bfb4069631f679e":{
      "scriptId":"u20"},
    "706abd30665040e58862a6f1825e46c9":{
      "scriptId":"u21"},
    "8d00789ecab347f5a590503a9a057a1c":{
      "scriptId":"u22"},
    "4005f4a6d86b427ba662c20abe3a4872":{
      "scriptId":"u23"},
    "1a50163171904dc1a219c6941f4910c6":{
      "scriptId":"u24"},
    "c92451cac32d459b99fa9900121bbd17":{
      "scriptId":"u25"},
    "1dcf2ee2de7842f48999655d5c35d448":{
      "scriptId":"u26"},
    "9c2cc1073cad46459b94bf2ffa52555e":{
      "scriptId":"u27"},
    "3e6d266afa0c4a1e99e22a8707b5e1b6":{
      "scriptId":"u28"},
    "48af5896cbdd43e79cc07cff8b03255b":{
      "scriptId":"u29"},
    "917dcd7390884b37aa1b271a339634d2":{
      "scriptId":"u30"},
    "322167e6027449ac8d45d42bff2214ec":{
      "scriptId":"u31"},
    "45b003454fb14668a6aee020ca209b08":{
      "scriptId":"u32"},
    "0ab59dcbcd62409dbf68f6c05f476c86":{
      "scriptId":"u33"},
    "d0746ad34aaf47b49ea336d24434176a":{
      "scriptId":"u34"},
    "c38c152492e94b058047014d0e6c9078":{
      "scriptId":"u35"},
    "70e1dab78bbe46938cd38fac57aeb9e7":{
      "scriptId":"u36"},
    "191cc26884034132b8e48584ede458ef":{
      "scriptId":"u37"},
    "3032e6b7cb234ee38a08c3b9c0379530":{
      "scriptId":"u38"},
    "a2bfabf0c03b4e14850664112cc3c4b1":{
      "scriptId":"u39"},
    "a21aa0e606b6421483e4d785b2934d30":{
      "scriptId":"u40"},
    "0b6ef40bb7d44623aafe3c715363defe":{
      "scriptId":"u41"},
    "dd6060136ec1426d957a7dabaedbf539":{
      "scriptId":"u42"},
    "6c24a937c1084a55bb2df29f58ea4132":{
      "scriptId":"u43"},
    "be9e67a12e91402ea5523a331d933701":{
      "scriptId":"u44"},
    "e7375eae01404999b331a2e51767a67b":{
      "scriptId":"u45"},
    "0702e119b6dc44deaee489f432b5f53b":{
      "scriptId":"u46"},
    "e570ea48c77942ebb90858186cbb010a":{
      "scriptId":"u47"},
    "d0752c8327f14852a7c5492906a7fddb":{
      "scriptId":"u48"},
    "9d6e72cdbd604b619e63db2c12b3187d":{
      "scriptId":"u49"},
    "ba38a2227b9f48c48c4b7b860a3845bd":{
      "scriptId":"u50"},
    "fe3699370f7c4076a9f4c5f6854db11b":{
      "scriptId":"u51"},
    "17deed3c3cd642288c693d4a00248dac":{
      "scriptId":"u52"},
    "4aea7836fe464d3493d63b7014b4c9c4":{
      "scriptId":"u53"},
    "b78f577017bf4ae7a54658ee69c7e55e":{
      "scriptId":"u54"},
    "ffcb4a315997478aa5cf5773d2376ffb":{
      "scriptId":"u55"},
    "a59226eaa3c0489db61ecfc67a6f85d8":{
      "scriptId":"u56"},
    "2c6f7f9d4d234e23b3c9f0286cc87606":{
      "scriptId":"u57"},
    "759b211fd6404f5994fd459a5eb536fa":{
      "scriptId":"u58"},
    "dd1f00af6ec64e249773f7572a72ef4e":{
      "scriptId":"u59"},
    "a861b20d62074d71b2ba30687ae0536b":{
      "scriptId":"u60"},
    "d6439999dbfb45e899f7865b716dec21":{
      "scriptId":"u61"},
    "eaf4f048d4084f74970c58947807293f":{
      "scriptId":"u62"},
    "f718256fb979403099244bec933ed3ad":{
      "scriptId":"u63"},
    "31c70f1e048f43668c1d97ea48ff6ec2":{
      "scriptId":"u64"},
    "2381672c63fa4b95bd282d267edb98c8":{
      "scriptId":"u65"},
    "f131a0b606ad40d39ad1420aa0ac0eca":{
      "scriptId":"u66"},
    "194579d07d924aa4bb426700b462259c":{
      "scriptId":"u67"},
    "ecb6fa4a1860427282e3684b517fe317":{
      "scriptId":"u68"},
    "7cdea9838b394bd3bd5bfd8c23abc933":{
      "scriptId":"u69"},
    "813e59856a48467a9b68e27cbf527b56":{
      "scriptId":"u70"},
    "6c94d75f6c454b13a92200b3db664510":{
      "scriptId":"u71"},
    "10a21b8c1ec44be8a9875026c85342e8":{
      "scriptId":"u72"},
    "d5d400e5598344eb83a429ad89ec8e66":{
      "scriptId":"u73"},
    "87d1db7f00e340c8b158183089d650f0":{
      "scriptId":"u74"},
    "56397ded24a04920a6d0e87dfe40f6e7":{
      "scriptId":"u75"},
    "bfc745d78fe24636b8a578c98649836d":{
      "scriptId":"u76"},
    "13aad8db36264b2ba758b97aefd0a6ef":{
      "scriptId":"u77"}}});