$axure.loadCurrentPage({
  "url":"个人中心_-_登录.html",
  "generationDate":new Date(1463988220794.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a1a8e3573044354b70033c71547e29e",
    "type":"Axure:Page",
    "name":"个人中心 - 登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"74cd07a4ad6f4d069419c0f6219309d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2890293df84c51ba8293930cad19cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"17b6c7ea7ae94e979558a398b11574a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff3cbf216be64cd4b3d5a725279584bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"d02192ab4c4744e281a7ce1730dc738c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7464d594fd2d451db6ce5862f25ed036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"ef8a35a3f74447dd9d8f9b06f14f332b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":91},
            "size":{
              "width":360,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d8b6b33611c42e88bbe25335060869c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":91},
                "size":{
                  "width":360,
                  "height":79},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心_-未登录/u6.png"}},
{
          "id":"03a009fb5e5647b8865d1f4bc61749a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":139},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbaf06558d8447fc818dd14cd9c358f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":139},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"999acf1ed8b34cfd89629cf255c3d531",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":178},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c3977577584002851a66ac00054719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":178},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u14.png"}},
{
          "id":"4c84d0e9818e4fd7925d3f3ca95d4165",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":217},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3da3f8a9ff414f90c1a2313c9d49a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":217},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心_-_登录/u12.png"}},
{
          "id":"36c585b27bc543dc8276b9853bdac924",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":264},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27909715ea84bb881afa8c2bdb5cfd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":264},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2155813af05443ecb91703f8ed5dd53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":264},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8161c1d409f49efb89cac7eb21e95bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":264},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12bbcf3eb1e54fda8cb11ba2408cbeca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":193,
              "y":264},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d54f8074d124c4ba3512f226a427349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":264},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60d4dc2a1ee94665be95a09f3443b1cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":277,
              "y":264},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87971570d14742ab8e81b49e35b051b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":264},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c79a9500a6a48ba93920842c3d92b94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":192},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e86c000b4164d41b850e55a2f79131c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":192},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2528ebd9a94d6a9ac104a1171c3453",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":285,
              "y":192},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da27f18aac5440c8a666dfb912a49c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":192},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb98ca4434e74cf9b90277ba4d2176eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":231},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269173c625724b2299ed869bb4191de8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":231},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心_-_登录/u26.png"}},
{
          "id":"c26abb4fe08b4df992de4b4109d6b168",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":231},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e666b807f164558985fee886981ef43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":231},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心_-_登录/u28.png"}},
{
          "id":"31a7a4d698054b75b9fb8f53ff03d739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":231},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf324fc27c1e4340ad289130acf4e653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":231},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心_-_登录/u30.png"}},
{
          "id":"d3bff0551b884ad9a9b3edcc18714354",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":231},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03445c75be0a4a789314f9cbfef6431e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":231},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心_-_登录/u32.png"}},
{
          "id":"7e522d5a8a504b158f3a28db2371c11d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":191},
            "size":{
              "width":25,
              "height":16},
            "rotation":"270",
            "textRotation":"270",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3554d3ee017414299bb7b54f43d26da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":191},
                "size":{
                  "width":25,
                  "height":16},
                "rotation":"270",
                "textRotation":"270",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"2e7a7a23697b42b8ba2edf6b382d4af5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":296},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc960ac86a34b0fa0e1e2890a3485b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":296},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认订单/u28.png"}},
{
          "id":"397b3a6d48774f9aa1a1608337020c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":312},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403156141a804cf7a1449ee11ee2063e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":312},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d669f90535648b3ac32d5be6d80b84a",
          "label":"tab条",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":445},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2fd5346b78ce47309d01b4c48239acc6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0cf8dd16202c455da341d604c330757c",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81bf4a20a25849e385eeba63a942b0b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 tab条 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["7d669f90535648b3ac32d5be6d80b84a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u55.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c2938352d15540b7a2bac1381d0ba5f6",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fa358c1156d3420591fc4110ad5e43cb",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":177},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4f9d5cb958d478f9d0091f9a8009133",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":177},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u57.png"}},
{
                  "id":"8a65c415ef7f4233a2738a20a6e51d52",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":16},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec6e28a4d32a4f2cbaabc3d7f913f519",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":16},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u59.png"}},
{
                  "id":"5b78c98f60bb4b9fbe9b565e1c264a73",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":19,
                      "y":43},
                    "size":{
                      "width":25,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2af5c88b6925491eaf832e53359ac353",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":19,
                          "y":43},
                        "size":{
                          "width":25,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cd3fd60d31584ba0a6d375a4a7b8ed33",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":73},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"485af8326b58468da9f76c0f778d19f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":73},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 购物车",
                              "target":{
                                "targetType":"page",
                                "url":"购物车.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u63.png"}},
{
                  "id":"f915a570fdef45218c095b3c51297cab",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":66,
                      "y":99},
                    "size":{
                      "width":37,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6407adba96e14280937ce0d3be9afda3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":66,
                          "y":99},
                        "size":{
                          "width":37,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a72860f695c4fbebb2661fb711a6966",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":118},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6427cf30b6f460083b521e4ea5e4509",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":118},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"未登录",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心 -未登录",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心_-未登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"登录",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心 - 登录",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心_-_登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u67.png"}},
{
                  "id":"568ab832c6f549a6a38350ecbee2b353",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":7,
                      "y":144},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"677f7d26ae8c4fda8329cdc611ff84b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":7,
                          "y":144},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"75498b1ebe994875be690a776713c226",
                  "label":"",
                  "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "location":{
                      "x":16,
                      "y":67},
                    "size":{
                      "width":22,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce22e6d079cc494c8022212cdc485088",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d669f90535648b3ac32d5be6d80b84a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "location":{
                          "x":16,
                          "y":67},
                        "size":{
                          "width":22,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 tab条 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["7d669f90535648b3ac32d5be6d80b84a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c6dc1ec76cb34dfaad23a97fa7de8120",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":33,
              "y":102},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9f86862723547ddbec559b2c13dbd26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":33,
                  "y":102},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心_-未登录/u39.png"}},
{
          "id":"251af00dabd34d128e0410b895d5698c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":124},
            "size":{
              "width":25,
              "height":16},
            "rotation":"270",
            "textRotation":"270",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3894ae2a5c324c58adec453ff8224638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":124},
                "size":{
                  "width":25,
                  "height":16},
                "rotation":"270",
                "textRotation":"270",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"0c4f4142c3744c56bc71b309c52cc2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":117,
              "y":117},
            "size":{
              "width":97,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"294ad64d165449b0b2c8b6449dc9c5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":117},
                "size":{
                  "width":97,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "74cd07a4ad6f4d069419c0f6219309d9":{
      "scriptId":"u0"},
    "6f2890293df84c51ba8293930cad19cd":{
      "scriptId":"u1"},
    "17b6c7ea7ae94e979558a398b11574a4":{
      "scriptId":"u2"},
    "ff3cbf216be64cd4b3d5a725279584bd":{
      "scriptId":"u3"},
    "d02192ab4c4744e281a7ce1730dc738c":{
      "scriptId":"u4"},
    "7464d594fd2d451db6ce5862f25ed036":{
      "scriptId":"u5"},
    "ef8a35a3f74447dd9d8f9b06f14f332b":{
      "scriptId":"u6"},
    "4d8b6b33611c42e88bbe25335060869c":{
      "scriptId":"u7"},
    "03a009fb5e5647b8865d1f4bc61749a9":{
      "scriptId":"u8"},
    "bbaf06558d8447fc818dd14cd9c358f7":{
      "scriptId":"u9"},
    "999acf1ed8b34cfd89629cf255c3d531":{
      "scriptId":"u10"},
    "23c3977577584002851a66ac00054719":{
      "scriptId":"u11"},
    "4c84d0e9818e4fd7925d3f3ca95d4165":{
      "scriptId":"u12"},
    "ea3da3f8a9ff414f90c1a2313c9d49a8":{
      "scriptId":"u13"},
    "36c585b27bc543dc8276b9853bdac924":{
      "scriptId":"u14"},
    "c27909715ea84bb881afa8c2bdb5cfd7":{
      "scriptId":"u15"},
    "2155813af05443ecb91703f8ed5dd53d":{
      "scriptId":"u16"},
    "a8161c1d409f49efb89cac7eb21e95bb":{
      "scriptId":"u17"},
    "12bbcf3eb1e54fda8cb11ba2408cbeca":{
      "scriptId":"u18"},
    "3d54f8074d124c4ba3512f226a427349":{
      "scriptId":"u19"},
    "60d4dc2a1ee94665be95a09f3443b1cd":{
      "scriptId":"u20"},
    "87971570d14742ab8e81b49e35b051b3":{
      "scriptId":"u21"},
    "2c79a9500a6a48ba93920842c3d92b94":{
      "scriptId":"u22"},
    "0e86c000b4164d41b850e55a2f79131c":{
      "scriptId":"u23"},
    "ee2528ebd9a94d6a9ac104a1171c3453":{
      "scriptId":"u24"},
    "da27f18aac5440c8a666dfb912a49c45":{
      "scriptId":"u25"},
    "eb98ca4434e74cf9b90277ba4d2176eb":{
      "scriptId":"u26"},
    "269173c625724b2299ed869bb4191de8":{
      "scriptId":"u27"},
    "c26abb4fe08b4df992de4b4109d6b168":{
      "scriptId":"u28"},
    "9e666b807f164558985fee886981ef43":{
      "scriptId":"u29"},
    "31a7a4d698054b75b9fb8f53ff03d739":{
      "scriptId":"u30"},
    "cf324fc27c1e4340ad289130acf4e653":{
      "scriptId":"u31"},
    "d3bff0551b884ad9a9b3edcc18714354":{
      "scriptId":"u32"},
    "03445c75be0a4a789314f9cbfef6431e":{
      "scriptId":"u33"},
    "7e522d5a8a504b158f3a28db2371c11d":{
      "scriptId":"u34"},
    "b3554d3ee017414299bb7b54f43d26da":{
      "scriptId":"u35"},
    "2e7a7a23697b42b8ba2edf6b382d4af5":{
      "scriptId":"u36"},
    "2fc960ac86a34b0fa0e1e2890a3485b2":{
      "scriptId":"u37"},
    "397b3a6d48774f9aa1a1608337020c96":{
      "scriptId":"u38"},
    "403156141a804cf7a1449ee11ee2063e":{
      "scriptId":"u39"},
    "7d669f90535648b3ac32d5be6d80b84a":{
      "scriptId":"u40"},
    "0cf8dd16202c455da341d604c330757c":{
      "scriptId":"u41"},
    "81bf4a20a25849e385eeba63a942b0b1":{
      "scriptId":"u42"},
    "fa358c1156d3420591fc4110ad5e43cb":{
      "scriptId":"u43"},
    "a4f9d5cb958d478f9d0091f9a8009133":{
      "scriptId":"u44"},
    "8a65c415ef7f4233a2738a20a6e51d52":{
      "scriptId":"u45"},
    "ec6e28a4d32a4f2cbaabc3d7f913f519":{
      "scriptId":"u46"},
    "5b78c98f60bb4b9fbe9b565e1c264a73":{
      "scriptId":"u47"},
    "2af5c88b6925491eaf832e53359ac353":{
      "scriptId":"u48"},
    "cd3fd60d31584ba0a6d375a4a7b8ed33":{
      "scriptId":"u49"},
    "485af8326b58468da9f76c0f778d19f8":{
      "scriptId":"u50"},
    "f915a570fdef45218c095b3c51297cab":{
      "scriptId":"u51"},
    "6407adba96e14280937ce0d3be9afda3":{
      "scriptId":"u52"},
    "8a72860f695c4fbebb2661fb711a6966":{
      "scriptId":"u53"},
    "a6427cf30b6f460083b521e4ea5e4509":{
      "scriptId":"u54"},
    "568ab832c6f549a6a38350ecbee2b353":{
      "scriptId":"u55"},
    "677f7d26ae8c4fda8329cdc611ff84b9":{
      "scriptId":"u56"},
    "75498b1ebe994875be690a776713c226":{
      "scriptId":"u57"},
    "ce22e6d079cc494c8022212cdc485088":{
      "scriptId":"u58"},
    "c6dc1ec76cb34dfaad23a97fa7de8120":{
      "scriptId":"u59"},
    "b9f86862723547ddbec559b2c13dbd26":{
      "scriptId":"u60"},
    "251af00dabd34d128e0410b895d5698c":{
      "scriptId":"u61"},
    "3894ae2a5c324c58adec453ff8224638":{
      "scriptId":"u62"},
    "0c4f4142c3744c56bc71b309c52cc2b3":{
      "scriptId":"u63"},
    "294ad64d165449b0b2c8b6449dc9c5cf":{
      "scriptId":"u64"}}});