$axure.loadCurrentPage({
  "url":"申请退货.html",
  "generationDate":new Date(1463988224222.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6000fe0858554eac99e67c51bdd69524",
    "type":"Axure:Page",
    "name":"申请退货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba071e8ae8c54b52965a8deb89b1975c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a3a4fe2ba841aaa15b759f6565f5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"cff5bf5b5d2b466191ba9a119a9d0c29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aba77d5623694b4c8b5d75e84f636ca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"6558126bea0d49989fffa531c938e558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2924344acd894ae285e0ad771663d118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"cacec7c1b82943d987847266c1828dd1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":57},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88553d0f736c49dca384f800c71fe023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":57},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"商品 - 已支付",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品 - 已支付",
                      "target":{
                        "targetType":"page",
                        "url":"商品_-_已支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"45943664dd964db1b2a278bdb8509faf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":120},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0521e5d6f7346888b30781c7fcdb806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":120},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8e1e12e7c3e413d99811dfdbea2e814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":15,
              "y":212},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d4c2216584c4c5abb718eb1aae39819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":15,
                  "y":212},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"292dda16a69549a2b4212bac49b9b791",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":137},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"ada9602f2c8d4f71a61ebd1ae849be07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":229},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"cd1f7700fabc4bd3831d51191d1129b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":15,
              "y":163},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3643eac7910482db253fe726b8f0327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":15,
                  "y":163},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15fe47f9449245688f7e7262d2884f14",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":181},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"35194d448451472c9d672589fe2a20a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":36,
              "y":253},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ca52ab53164b4db88df3b96c4a3835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":36,
                  "y":253},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"2d61ff540d744dc2bae0158eea7683ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":36,
              "y":288},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ba596e002fe47a19a97e8a0244e99e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":36,
                  "y":288},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"ac9595ef33b14ea9ae17af12be033bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":36,
              "y":323},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf9f25fb509a4e2aa2cbc49e25337507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":36,
                  "y":323},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"3ff8592a1f5f438a84d0eedfe05a8407",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":36,
              "y":358},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca9a5f2977349d4a7ada113ebab7e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":36,
                  "y":358},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"d1dfc9115b2e4641b4fc200f39b1655c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":197,
              "y":253},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6ba33d865e34214aef91e42ef6d4032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":197,
                  "y":253},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"d21c8f0848014223a5baddddced528f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":197,
              "y":288},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7964c87a0c714d53a5291106fbe2b92a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":197,
                  "y":288},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"5a2a155b55de45058c49453a4425e397",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":197,
              "y":323},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e2975b2e003446fb9c4b08aa4ca39e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":197,
                  "y":323},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"b01375d8f50f45379fa504704c67d07e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":197,
              "y":358},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ab9aebde3e044dcae7bdbd81942d0a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":197,
                  "y":358},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"80a40a0cd711479b8cbb063d5eee31bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":592},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc3740ff3f934aec949161e43ba4bd6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":592},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"8cfa5df1bea44139b35433fe1b54841a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":163},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82872ed12ba2412aaa576e4787dee09e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":163},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48eb2845bf9c41739450d3249fea5f1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":22,
              "y":499},
            "size":{
              "width":313,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8810dc5f28f4f34b80b3555b13ad12b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":22,
                  "y":499},
                "size":{
                  "width":313,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edf47e03608c489495888aa345061dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":92,
              "y":213},
            "size":{
              "width":157,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"113a9797a0e8430f95d2a603e3adaa38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":213},
                "size":{
                  "width":157,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88d9956a4f8742a89e7ac09409f37fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":780,
              "y":0},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d0da84fa2744359b432503c830b8564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":780,
                  "y":0},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"58acab6732b4412d985a2b8396677258",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":0},
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59c215b1038b44f686e95c8411e7ed54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":0},
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"6b4a6502f4984620bc74b4b169976d44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e6705344390489bbd5f7d4407180390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"f62c5779ba724666a4db9463045bfad6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":57},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53811f3e2a8b4e009e043df8d2480f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":57},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"商品 - 已支付",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品 - 已支付",
                      "target":{
                        "targetType":"page",
                        "url":"商品_-_已支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"d3f0c7d5917c4d9393162d462625dbcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":121},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46df73eaf3924541b7c085a678473a27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":795,
                  "y":121},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38a3dcc2e94f4436a309e9dd1292d78f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":795,
              "y":212},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"865d30e46dc24503bfa03a21687129a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":795,
                  "y":212},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60493f75cff045d59654a4c9fc1c06fa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":137},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"ef25c79a36b24caa8b5053c8f68e205a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":229},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"f82284b9c9034bf789b664852a60e576",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":795,
              "y":163},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c35b18a09a4c8093ce568a3b669692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":795,
                  "y":163},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b1460846974d19808c3f486fbd7fa0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":181},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"2d79c49d12394e4686bc43a54dbebd80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":253},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d8740d80ec407ca87319b0ce995d72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":253},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"f5c5e8e9b1214d44a3c6681bfea33d72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":288},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1027a581b4934885831907b5bdfc0d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":288},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"6c3c2e512cc64b3c86ac75be7a7a5667",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":323},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86f68d69b4e4868a263a24a985ea119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":323},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"24832ede2e244f5d9f50a30d87321206",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":358},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee68f9be822a4490aa3c065988206905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":358},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"b8d2321b084c447387ed03b0def9a181",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":977,
              "y":253},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a888396c9514f4eb75a16858cf8513b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":977,
                  "y":253},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"86931bd023324e6b97ae97b00714002b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":977,
              "y":288},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14651cdee9004cda94ada503353fb0d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":977,
                  "y":288},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"c9db1b4bb7d54062a1fe945da873c4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":977,
              "y":323},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b74399e4904086a31ce7dde6034619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":977,
                  "y":323},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"b43632da7cad48f28f586cdfea0e883d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":977,
              "y":358},
            "size":{
              "width":129,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718c3557a31949e09e3813648d2606c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":977,
                  "y":358},
                "size":{
                  "width":129,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u17.png"}},
{
          "id":"447c8e0c304d478b98690a5b7c2d7471",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":592},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"579f823a64e44e8e94a15b6c3a0f10f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":592},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"c6718176fd21410c9dde30c71b6a6d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":872,
              "y":163},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec776d4fc5894f5e8f4fe89317b0ef57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":872,
                  "y":163},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab147996d7d241808ed929b17d3281f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":802,
              "y":503},
            "size":{
              "width":313,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7552c19ced34af4ad49f06cf9416ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":802,
                  "y":503},
                "size":{
                  "width":313,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f32da59e58a4a6cb0f9dd563e207a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":872,
              "y":122},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"957f6610703441668fed1770ae9be76a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":872,
                  "y":122},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03fc27b06a1f4f62834fc221ae7f69b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":872,
              "y":213},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bff0478a7c09476b942ce2701ce06381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":872,
                  "y":213},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10ab2e3499a64b5d8ea66977830fef5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":84,
              "y":670},
            "size":{
              "width":177,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"863a04b2250b4c079418b17c4e03df97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":84,
                  "y":670},
                "size":{
                  "width":177,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"909c343f0b36484c9352449aafdbbc84",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":870,
              "y":670},
            "size":{
              "width":201,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19430f6128be4a3fb6313aeffb2f9023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":870,
                  "y":670},
                "size":{
                  "width":201,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7e23fbb3402470598f82cf0231b101d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":96,
              "y":120},
            "size":{
              "width":69,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad41f94b70e144c49eb4a13653edc43f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":96,
                  "y":120},
                "size":{
                  "width":69,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c011a1786b224d01b7d2372bad953292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":21,
              "y":403},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea8fa6f01d4c4d8193b9d3e6bcf4eab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":21,
                  "y":403},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"589ae0463fba496794211f715c7fc472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":425},
            "size":{
              "width":319,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8640084dc874a9283a11d2e168d93c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":425},
                "size":{
                  "width":319,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u92.png"}},
{
          "id":"d9cd6cdb5de643798a8ffc4916bfe0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":800,
              "y":403},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29a56eb8a234bf8a6697e755766f7c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":800,
                  "y":403},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98da77dd147b4d6589c9ec94d7b4cbfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":425},
            "size":{
              "width":319,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d8a0fc50a3a444e99e103dda42296ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":425},
                "size":{
                  "width":319,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u92.png"}},
{
          "id":"0d58a1c3078a48b19f15cbc46aed0372",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":34,
              "y":433},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c4dc2fad4245c09df30684b855418a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":433},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24324589aed0496b92cb1eabafbc1149",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":433},
            "size":{
              "width":181,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5570d4908a144dab04dba463cbd5db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":433},
                "size":{
                  "width":181,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aa7040214ed44849c883fe0ae6a9d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":391,
              "y":0},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a007f54fec24452bae6a9200eec347b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":391,
                  "y":0},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"e9fecbf88e434dbf9dc23fa4c4556119",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":0},
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dcf7ac05c824715bb1fabf36631d3ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":0},
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"2e3afb71b15e4ab09be46ecfaeeb0c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb9881e342a454ca8cb016d6b6dbdb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"f754534836f54512b52a11c2dfcb8021",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":57},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d278af7041450daf7ac14a476dfa75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":57},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"fe71f45ae5644f75aee4989ffa8c5ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":108},
            "size":{
              "width":330,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a543e4c42b941b6bbea3ee37c617d18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":407,
                  "y":108},
                "size":{
                  "width":330,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u110.png"}},
{
          "id":"062c69bbb1594ad0892a15971931fe43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":421,
              "y":120},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a736c491fe4b4ed9a867ce7704c17420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":120},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c40e8afa16d44978b9be26db9224b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":370},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8c441b58fb749e3b134b88f1a4232e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":370},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请退货/u114.png"}},
{
          "id":"84cf29b9e9494cd481e3420333e0db1d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":463},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d0e534a27740b8825635145ae28e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":463},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"eb829c84c7e04d95b6dae29b2920444f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":390},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a64af8597e470ca34be956a875a522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":390},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"9a5515b831a44c93b2b9d9eb49f0ce6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":486,
              "y":670},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f66c70e43b0b4eb19c91c5bb1ed6a0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":486,
                  "y":670},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ba071e8ae8c54b52965a8deb89b1975c":{
      "scriptId":"u0"},
    "f4a3a4fe2ba841aaa15b759f6565f5f1":{
      "scriptId":"u1"},
    "cff5bf5b5d2b466191ba9a119a9d0c29":{
      "scriptId":"u2"},
    "aba77d5623694b4c8b5d75e84f636ca7":{
      "scriptId":"u3"},
    "6558126bea0d49989fffa531c938e558":{
      "scriptId":"u4"},
    "2924344acd894ae285e0ad771663d118":{
      "scriptId":"u5"},
    "cacec7c1b82943d987847266c1828dd1":{
      "scriptId":"u6"},
    "88553d0f736c49dca384f800c71fe023":{
      "scriptId":"u7"},
    "45943664dd964db1b2a278bdb8509faf":{
      "scriptId":"u8"},
    "a0521e5d6f7346888b30781c7fcdb806":{
      "scriptId":"u9"},
    "c8e1e12e7c3e413d99811dfdbea2e814":{
      "scriptId":"u10"},
    "1d4c2216584c4c5abb718eb1aae39819":{
      "scriptId":"u11"},
    "292dda16a69549a2b4212bac49b9b791":{
      "scriptId":"u12"},
    "ada9602f2c8d4f71a61ebd1ae849be07":{
      "scriptId":"u13"},
    "cd1f7700fabc4bd3831d51191d1129b9":{
      "scriptId":"u14"},
    "e3643eac7910482db253fe726b8f0327":{
      "scriptId":"u15"},
    "15fe47f9449245688f7e7262d2884f14":{
      "scriptId":"u16"},
    "35194d448451472c9d672589fe2a20a8":{
      "scriptId":"u17"},
    "a5ca52ab53164b4db88df3b96c4a3835":{
      "scriptId":"u18"},
    "2d61ff540d744dc2bae0158eea7683ae":{
      "scriptId":"u19"},
    "0ba596e002fe47a19a97e8a0244e99e0":{
      "scriptId":"u20"},
    "ac9595ef33b14ea9ae17af12be033bd4":{
      "scriptId":"u21"},
    "bf9f25fb509a4e2aa2cbc49e25337507":{
      "scriptId":"u22"},
    "3ff8592a1f5f438a84d0eedfe05a8407":{
      "scriptId":"u23"},
    "3ca9a5f2977349d4a7ada113ebab7e4c":{
      "scriptId":"u24"},
    "d1dfc9115b2e4641b4fc200f39b1655c":{
      "scriptId":"u25"},
    "b6ba33d865e34214aef91e42ef6d4032":{
      "scriptId":"u26"},
    "d21c8f0848014223a5baddddced528f9":{
      "scriptId":"u27"},
    "7964c87a0c714d53a5291106fbe2b92a":{
      "scriptId":"u28"},
    "5a2a155b55de45058c49453a4425e397":{
      "scriptId":"u29"},
    "8e2975b2e003446fb9c4b08aa4ca39e5":{
      "scriptId":"u30"},
    "b01375d8f50f45379fa504704c67d07e":{
      "scriptId":"u31"},
    "4ab9aebde3e044dcae7bdbd81942d0a2":{
      "scriptId":"u32"},
    "80a40a0cd711479b8cbb063d5eee31bd":{
      "scriptId":"u33"},
    "bc3740ff3f934aec949161e43ba4bd6e":{
      "scriptId":"u34"},
    "8cfa5df1bea44139b35433fe1b54841a":{
      "scriptId":"u35"},
    "82872ed12ba2412aaa576e4787dee09e":{
      "scriptId":"u36"},
    "48eb2845bf9c41739450d3249fea5f1d":{
      "scriptId":"u37"},
    "f8810dc5f28f4f34b80b3555b13ad12b":{
      "scriptId":"u38"},
    "edf47e03608c489495888aa345061dc0":{
      "scriptId":"u39"},
    "113a9797a0e8430f95d2a603e3adaa38":{
      "scriptId":"u40"},
    "88d9956a4f8742a89e7ac09409f37fda":{
      "scriptId":"u41"},
    "9d0da84fa2744359b432503c830b8564":{
      "scriptId":"u42"},
    "58acab6732b4412d985a2b8396677258":{
      "scriptId":"u43"},
    "59c215b1038b44f686e95c8411e7ed54":{
      "scriptId":"u44"},
    "6b4a6502f4984620bc74b4b169976d44":{
      "scriptId":"u45"},
    "3e6705344390489bbd5f7d4407180390":{
      "scriptId":"u46"},
    "f62c5779ba724666a4db9463045bfad6":{
      "scriptId":"u47"},
    "53811f3e2a8b4e009e043df8d2480f64":{
      "scriptId":"u48"},
    "d3f0c7d5917c4d9393162d462625dbcd":{
      "scriptId":"u49"},
    "46df73eaf3924541b7c085a678473a27":{
      "scriptId":"u50"},
    "38a3dcc2e94f4436a309e9dd1292d78f":{
      "scriptId":"u51"},
    "865d30e46dc24503bfa03a21687129a8":{
      "scriptId":"u52"},
    "60493f75cff045d59654a4c9fc1c06fa":{
      "scriptId":"u53"},
    "ef25c79a36b24caa8b5053c8f68e205a":{
      "scriptId":"u54"},
    "f82284b9c9034bf789b664852a60e576":{
      "scriptId":"u55"},
    "96c35b18a09a4c8093ce568a3b669692":{
      "scriptId":"u56"},
    "86b1460846974d19808c3f486fbd7fa0":{
      "scriptId":"u57"},
    "2d79c49d12394e4686bc43a54dbebd80":{
      "scriptId":"u58"},
    "39d8740d80ec407ca87319b0ce995d72":{
      "scriptId":"u59"},
    "f5c5e8e9b1214d44a3c6681bfea33d72":{
      "scriptId":"u60"},
    "1027a581b4934885831907b5bdfc0d5b":{
      "scriptId":"u61"},
    "6c3c2e512cc64b3c86ac75be7a7a5667":{
      "scriptId":"u62"},
    "b86f68d69b4e4868a263a24a985ea119":{
      "scriptId":"u63"},
    "24832ede2e244f5d9f50a30d87321206":{
      "scriptId":"u64"},
    "ee68f9be822a4490aa3c065988206905":{
      "scriptId":"u65"},
    "b8d2321b084c447387ed03b0def9a181":{
      "scriptId":"u66"},
    "9a888396c9514f4eb75a16858cf8513b":{
      "scriptId":"u67"},
    "86931bd023324e6b97ae97b00714002b":{
      "scriptId":"u68"},
    "14651cdee9004cda94ada503353fb0d2":{
      "scriptId":"u69"},
    "c9db1b4bb7d54062a1fe945da873c4dc":{
      "scriptId":"u70"},
    "f4b74399e4904086a31ce7dde6034619":{
      "scriptId":"u71"},
    "b43632da7cad48f28f586cdfea0e883d":{
      "scriptId":"u72"},
    "718c3557a31949e09e3813648d2606c6":{
      "scriptId":"u73"},
    "447c8e0c304d478b98690a5b7c2d7471":{
      "scriptId":"u74"},
    "579f823a64e44e8e94a15b6c3a0f10f2":{
      "scriptId":"u75"},
    "c6718176fd21410c9dde30c71b6a6d3f":{
      "scriptId":"u76"},
    "ec776d4fc5894f5e8f4fe89317b0ef57":{
      "scriptId":"u77"},
    "ab147996d7d241808ed929b17d3281f1":{
      "scriptId":"u78"},
    "f7552c19ced34af4ad49f06cf9416ae1":{
      "scriptId":"u79"},
    "5f32da59e58a4a6cb0f9dd563e207a09":{
      "scriptId":"u80"},
    "957f6610703441668fed1770ae9be76a":{
      "scriptId":"u81"},
    "03fc27b06a1f4f62834fc221ae7f69b5":{
      "scriptId":"u82"},
    "bff0478a7c09476b942ce2701ce06381":{
      "scriptId":"u83"},
    "10ab2e3499a64b5d8ea66977830fef5d":{
      "scriptId":"u84"},
    "863a04b2250b4c079418b17c4e03df97":{
      "scriptId":"u85"},
    "909c343f0b36484c9352449aafdbbc84":{
      "scriptId":"u86"},
    "19430f6128be4a3fb6313aeffb2f9023":{
      "scriptId":"u87"},
    "a7e23fbb3402470598f82cf0231b101d":{
      "scriptId":"u88"},
    "ad41f94b70e144c49eb4a13653edc43f":{
      "scriptId":"u89"},
    "c011a1786b224d01b7d2372bad953292":{
      "scriptId":"u90"},
    "ea8fa6f01d4c4d8193b9d3e6bcf4eab4":{
      "scriptId":"u91"},
    "589ae0463fba496794211f715c7fc472":{
      "scriptId":"u92"},
    "e8640084dc874a9283a11d2e168d93c0":{
      "scriptId":"u93"},
    "d9cd6cdb5de643798a8ffc4916bfe0d6":{
      "scriptId":"u94"},
    "a29a56eb8a234bf8a6697e755766f7c1":{
      "scriptId":"u95"},
    "98da77dd147b4d6589c9ec94d7b4cbfa":{
      "scriptId":"u96"},
    "9d8a0fc50a3a444e99e103dda42296ee":{
      "scriptId":"u97"},
    "0d58a1c3078a48b19f15cbc46aed0372":{
      "scriptId":"u98"},
    "50c4dc2fad4245c09df30684b855418a":{
      "scriptId":"u99"},
    "24324589aed0496b92cb1eabafbc1149":{
      "scriptId":"u100"},
    "e5570d4908a144dab04dba463cbd5db5":{
      "scriptId":"u101"},
    "2aa7040214ed44849c883fe0ae6a9d3b":{
      "scriptId":"u102"},
    "a007f54fec24452bae6a9200eec347b8":{
      "scriptId":"u103"},
    "e9fecbf88e434dbf9dc23fa4c4556119":{
      "scriptId":"u104"},
    "4dcf7ac05c824715bb1fabf36631d3ff":{
      "scriptId":"u105"},
    "2e3afb71b15e4ab09be46ecfaeeb0c92":{
      "scriptId":"u106"},
    "beb9881e342a454ca8cb016d6b6dbdb5":{
      "scriptId":"u107"},
    "f754534836f54512b52a11c2dfcb8021":{
      "scriptId":"u108"},
    "73d278af7041450daf7ac14a476dfa75":{
      "scriptId":"u109"},
    "fe71f45ae5644f75aee4989ffa8c5ba8":{
      "scriptId":"u110"},
    "6a543e4c42b941b6bbea3ee37c617d18":{
      "scriptId":"u111"},
    "062c69bbb1594ad0892a15971931fe43":{
      "scriptId":"u112"},
    "a736c491fe4b4ed9a867ce7704c17420":{
      "scriptId":"u113"},
    "6c40e8afa16d44978b9be26db9224b2d":{
      "scriptId":"u114"},
    "a8c441b58fb749e3b134b88f1a4232e3":{
      "scriptId":"u115"},
    "84cf29b9e9494cd481e3420333e0db1d":{
      "scriptId":"u116"},
    "21d0e534a27740b8825635145ae28e8a":{
      "scriptId":"u117"},
    "eb829c84c7e04d95b6dae29b2920444f":{
      "scriptId":"u118"},
    "14a64af8597e470ca34be956a875a522":{
      "scriptId":"u119"},
    "9a5515b831a44c93b2b9d9eb49f0ce6e":{
      "scriptId":"u120"},
    "f66c70e43b0b4eb19c91c5bb1ed6a0f3":{
      "scriptId":"u121"}}});