$axure.loadCurrentPage({
  "url":"昵称.html",
  "generationDate":new Date(1463988221107.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8402e7971b1d4b2c8ce14eb070d5f3f3",
    "type":"Axure:Page",
    "name":"昵称",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9ae559715004838836e145baf192d0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27cff0656dac4854a295d3124a20639c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"d06132fe151e4b3bb7ebebbbe4512795",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96efb4fd264475f9517cd4a3d5b26cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"99d284f1929943398280834d926809cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a8e053a8dda42e289e4e46231a5ee44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"d0ff09b405d741ca9a8364e4b6e33a99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc1a04193dc48fbb19b81ee19f62ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"0224ffffdbc64feba5d446239eec8063",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":109},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"bda65c0325004a7da288978598bbce29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":158},
            "size":{
              "width":235,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"057ab79176e64349b8abfcacb19bd42d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":158},
                "size":{
                  "width":235,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3396f64f5fd472590412d61ac78bcd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":200},
            "size":{
              "width":340,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ece3319c0f4d6dad4723bfe66b52f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":200},
                "size":{
                  "width":340,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9ae559715004838836e145baf192d0d":{
      "scriptId":"u0"},
    "27cff0656dac4854a295d3124a20639c":{
      "scriptId":"u1"},
    "d06132fe151e4b3bb7ebebbbe4512795":{
      "scriptId":"u2"},
    "e96efb4fd264475f9517cd4a3d5b26cc":{
      "scriptId":"u3"},
    "99d284f1929943398280834d926809cf":{
      "scriptId":"u4"},
    "8a8e053a8dda42e289e4e46231a5ee44":{
      "scriptId":"u5"},
    "d0ff09b405d741ca9a8364e4b6e33a99":{
      "scriptId":"u6"},
    "4bc1a04193dc48fbb19b81ee19f62ef1":{
      "scriptId":"u7"},
    "0224ffffdbc64feba5d446239eec8063":{
      "scriptId":"u8"},
    "bda65c0325004a7da288978598bbce29":{
      "scriptId":"u9"},
    "057ab79176e64349b8abfcacb19bd42d":{
      "scriptId":"u10"},
    "a3396f64f5fd472590412d61ac78bcd1":{
      "scriptId":"u11"},
    "11ece3319c0f4d6dad4723bfe66b52f4":{
      "scriptId":"u12"}}});