$axure.loadCurrentPage({
  "url":"确认订单.html",
  "generationDate":new Date(1463988217666.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54af2942e46a4b8fb60cf48dffe49d4c",
    "type":"Axure:Page",
    "name":"确认订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89af18c6cb3945b098cfb9aa95b99f05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef516f82f13249dc9f49d10b472b44e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"1b759e91cad24db0982f13a4dc553fca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bb956a3850a4d42a1204df02bc1cc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"2ec3c54074c242c38d2a6e42daba1bd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cafb8a304fc4325986545af083d2633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"a0e904dda02a4bf38054ca6a22f4ffb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e843f08330744fe2871a4fd47783a0fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"e4edbd692ab844f9a8d7f7d6484e4009",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":111},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d58ef979daa4a6d9587da980174a621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":111},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83fac5a1126046c5b8c7703720e2b244",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":108},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eee296aead04c05a5e3f28dc3d0ec28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":108},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u10.png"}},
{
          "id":"776964e869f84d5d9ea4e1b99e8d8a16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":148},
            "size":{
              "width":360,
              "height":212},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a6398b83944721b33e1303d4fcbb6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":148},
                "size":{
                  "width":360,
                  "height":212},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u12.png"}},
{
          "id":"84a497236d424da5905aaa14cf2f0ab5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":185},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"bbfda13031cb4180bfe4571552688542",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":157},
            "size":{
              "width":58,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feae014042ac4c108b569e3fb8dd050a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":157},
                "size":{
                  "width":58,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u15.png"}},
{
          "id":"7c734db2357940cca1819e1a1a4a1532",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":162},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a59e476322de4f669f3fef13e336b2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":162},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"999eb880a8d4459d9370bfeed473daa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":199},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b83c940542b4f8b84eab97ed0eb504a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":199},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u19.png"}},
{
          "id":"139e386d98b94d7ba9f48bac017b4bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":73,
              "y":203},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcb07781627648a29441e08ca229c961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":73,
                  "y":203},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"104d965a1ada46b3bc3cd4de6b40f4ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":253},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"0d2888f26b374b5eaa0fe58c7880972b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":203},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d971e8515a7642568afcbd2c7f7fcc8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":203},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6164e8d6075c4d4590f2589e3b580d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":15,
              "y":322},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e091f3e06a04cd497facb6ae7b985f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":322},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4bd9a7a18d94b8897343ae504112e11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":590},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a7fd54a27b64c3a80013b9521e3d72e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":590},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u28.png"}},
{
          "id":"e17222ff75c14d278bc4dcfaadd7a0c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":15,
              "y":607},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2322b1d5bb6e492e9494c17b8fe5d29f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":607},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1e8a0e9865b4d70b8b2399b8e0e0bdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":270,
              "y":598},
            "size":{
              "width":81,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2218732ef14135b7df074f28f1e553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":270,
                  "y":598},
                "size":{
                  "width":81,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付",
                      "target":{
                        "targetType":"page",
                        "url":"支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认订单/u32.png"}},
{
          "id":"e6e7680ecdff42a3807ddd40a83c0e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":237},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a073fed4f17940f8aaaffe86e687f3a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":237},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5c9dee8bb034375aaf269aff9ca3119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":325,
              "y":322},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fb5058b0cb14561b2fd4dfa73bcbb57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":322},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7214976dea949dfad5f1d280a71d1cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a9390004d44dc58e4087c684c896cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卡券详情",
                      "target":{
                        "targetType":"page",
                        "url":"卡券详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"5768fbbb094048bd947c5ca8df401341",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":189,
              "y":269},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"968a90d476264e4da02e00703c95cbb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":189,
                  "y":269},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u40.png"}},
{
          "id":"0a597288e8f5471ebc5f827a0595fbb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":283,
              "y":269},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bcea1d857d241b5a77ad80eb6f726f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":269},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u40.png"}},
{
          "id":"e9c73f251b6849cca478b1e593502c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":261,
              "y":272},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c278caea1bf84e90bf008d692d13eab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":261,
                  "y":272},
                "size":{
                  "width":10,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2582074dc12409e9f5cd9b9b5aaf8b8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":298},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u46_line.png"}},
{
          "id":"ab3742484a2347808b6cb67d642c5f98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":405,
              "y":268},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa1719ad19af4ddcaa082c524fca4349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":405,
                  "y":268},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u40.png"}},
{
          "id":"94a2fa6c681e49df8d4710e04d10470d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":499,
              "y":268},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63043019bc01425fbe995681587c0ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":499,
                  "y":268},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u40.png"}},
{
          "id":"2eedf759c60149dc8c22385f1edc3e02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":477,
              "y":271},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac905ac85584b2a9b774cee4f194f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":477,
                  "y":271},
                "size":{
                  "width":10,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af226199546349ddbfa7e980c1b031b7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":610},
            "size":{
              "width":59,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/确认订单/u53_end.png",
            "line~":"images/确认订单/u53_line.png"}},
{
          "id":"933bdd2b3b6541f78d79bcfaea8dc5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":408,
              "y":605},
            "size":{
              "width":512,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d97796390f146548cc286e32c211896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":408,
                  "y":605},
                "size":{
                  "width":512,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5d93f62f2564ccca268267b527a64d1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":275},
            "size":{
              "width":59,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/确认订单/u53_end.png",
            "line~":"images/确认订单/u53_line.png"}},
{
          "id":"e900740300ce4c13a886bb71f742257f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":569,
              "y":270},
            "size":{
              "width":497,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c47ba563be4357937e2b2c44dd5a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":569,
                  "y":270},
                "size":{
                  "width":497,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60eaec24f64c4681adf06cc6a66ca909",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":340},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774d6a04195a45809a9b21d04e46fbd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":631,
                  "y":340},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u59.png"}},
{
          "id":"beabfeab99da46019868a4240e212ef6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":270},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb10355247824f4dab3b4bb48f76ecd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":270},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"4f04ed4ef8b84cc4bac69d44591c46d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":376,
              "y":219},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4921b68dbec4a23bf06591f747a91db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":376,
                  "y":219},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4412b70df1b94e57bad966d8d2fdb607",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":290},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96382451601343409c91f739a9e1b031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":290},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"20d8491a12dd40debfd1d5c53dea0f63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":384,
              "y":322},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8df90c1db204e538d66349b1ec8c071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":322},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "89af18c6cb3945b098cfb9aa95b99f05":{
      "scriptId":"u0"},
    "ef516f82f13249dc9f49d10b472b44e7":{
      "scriptId":"u1"},
    "1b759e91cad24db0982f13a4dc553fca":{
      "scriptId":"u2"},
    "1bb956a3850a4d42a1204df02bc1cc25":{
      "scriptId":"u3"},
    "2ec3c54074c242c38d2a6e42daba1bd0":{
      "scriptId":"u4"},
    "6cafb8a304fc4325986545af083d2633":{
      "scriptId":"u5"},
    "a0e904dda02a4bf38054ca6a22f4ffb9":{
      "scriptId":"u6"},
    "e843f08330744fe2871a4fd47783a0fb":{
      "scriptId":"u7"},
    "e4edbd692ab844f9a8d7f7d6484e4009":{
      "scriptId":"u8"},
    "3d58ef979daa4a6d9587da980174a621":{
      "scriptId":"u9"},
    "83fac5a1126046c5b8c7703720e2b244":{
      "scriptId":"u10"},
    "5eee296aead04c05a5e3f28dc3d0ec28":{
      "scriptId":"u11"},
    "776964e869f84d5d9ea4e1b99e8d8a16":{
      "scriptId":"u12"},
    "59a6398b83944721b33e1303d4fcbb6e":{
      "scriptId":"u13"},
    "84a497236d424da5905aaa14cf2f0ab5":{
      "scriptId":"u14"},
    "bbfda13031cb4180bfe4571552688542":{
      "scriptId":"u15"},
    "feae014042ac4c108b569e3fb8dd050a":{
      "scriptId":"u16"},
    "7c734db2357940cca1819e1a1a4a1532":{
      "scriptId":"u17"},
    "a59e476322de4f669f3fef13e336b2ae":{
      "scriptId":"u18"},
    "999eb880a8d4459d9370bfeed473daa8":{
      "scriptId":"u19"},
    "8b83c940542b4f8b84eab97ed0eb504a":{
      "scriptId":"u20"},
    "139e386d98b94d7ba9f48bac017b4bb0":{
      "scriptId":"u21"},
    "dcb07781627648a29441e08ca229c961":{
      "scriptId":"u22"},
    "104d965a1ada46b3bc3cd4de6b40f4ed":{
      "scriptId":"u23"},
    "0d2888f26b374b5eaa0fe58c7880972b":{
      "scriptId":"u24"},
    "d971e8515a7642568afcbd2c7f7fcc8e":{
      "scriptId":"u25"},
    "6164e8d6075c4d4590f2589e3b580d3d":{
      "scriptId":"u26"},
    "4e091f3e06a04cd497facb6ae7b985f6":{
      "scriptId":"u27"},
    "e4bd9a7a18d94b8897343ae504112e11":{
      "scriptId":"u28"},
    "7a7fd54a27b64c3a80013b9521e3d72e":{
      "scriptId":"u29"},
    "e17222ff75c14d278bc4dcfaadd7a0c3":{
      "scriptId":"u30"},
    "2322b1d5bb6e492e9494c17b8fe5d29f":{
      "scriptId":"u31"},
    "e1e8a0e9865b4d70b8b2399b8e0e0bdd":{
      "scriptId":"u32"},
    "4f2218732ef14135b7df074f28f1e553":{
      "scriptId":"u33"},
    "e6e7680ecdff42a3807ddd40a83c0e85":{
      "scriptId":"u34"},
    "a073fed4f17940f8aaaffe86e687f3a0":{
      "scriptId":"u35"},
    "e5c9dee8bb034375aaf269aff9ca3119":{
      "scriptId":"u36"},
    "5fb5058b0cb14561b2fd4dfa73bcbb57":{
      "scriptId":"u37"},
    "f7214976dea949dfad5f1d280a71d1cd":{
      "scriptId":"u38"},
    "39a9390004d44dc58e4087c684c896cd":{
      "scriptId":"u39"},
    "5768fbbb094048bd947c5ca8df401341":{
      "scriptId":"u40"},
    "968a90d476264e4da02e00703c95cbb4":{
      "scriptId":"u41"},
    "0a597288e8f5471ebc5f827a0595fbb9":{
      "scriptId":"u42"},
    "4bcea1d857d241b5a77ad80eb6f726f5":{
      "scriptId":"u43"},
    "e9c73f251b6849cca478b1e593502c28":{
      "scriptId":"u44"},
    "c278caea1bf84e90bf008d692d13eab6":{
      "scriptId":"u45"},
    "d2582074dc12409e9f5cd9b9b5aaf8b8":{
      "scriptId":"u46"},
    "ab3742484a2347808b6cb67d642c5f98":{
      "scriptId":"u47"},
    "fa1719ad19af4ddcaa082c524fca4349":{
      "scriptId":"u48"},
    "94a2fa6c681e49df8d4710e04d10470d":{
      "scriptId":"u49"},
    "63043019bc01425fbe995681587c0ca2":{
      "scriptId":"u50"},
    "2eedf759c60149dc8c22385f1edc3e02":{
      "scriptId":"u51"},
    "3ac905ac85584b2a9b774cee4f194f94":{
      "scriptId":"u52"},
    "af226199546349ddbfa7e980c1b031b7":{
      "scriptId":"u53"},
    "933bdd2b3b6541f78d79bcfaea8dc5b1":{
      "scriptId":"u54"},
    "5d97796390f146548cc286e32c211896":{
      "scriptId":"u55"},
    "d5d93f62f2564ccca268267b527a64d1":{
      "scriptId":"u56"},
    "e900740300ce4c13a886bb71f742257f":{
      "scriptId":"u57"},
    "94c47ba563be4357937e2b2c44dd5a15":{
      "scriptId":"u58"},
    "60eaec24f64c4681adf06cc6a66ca909":{
      "scriptId":"u59"},
    "774d6a04195a45809a9b21d04e46fbd9":{
      "scriptId":"u60"},
    "beabfeab99da46019868a4240e212ef6":{
      "scriptId":"u61"},
    "cb10355247824f4dab3b4bb48f76ecd9":{
      "scriptId":"u62"},
    "4f04ed4ef8b84cc4bac69d44591c46d0":{
      "scriptId":"u63"},
    "c4921b68dbec4a23bf06591f747a91db":{
      "scriptId":"u64"},
    "4412b70df1b94e57bad966d8d2fdb607":{
      "scriptId":"u65"},
    "96382451601343409c91f739a9e1b031":{
      "scriptId":"u66"},
    "20d8491a12dd40debfd1d5c53dea0f63":{
      "scriptId":"u67"},
    "e8df90c1db204e538d66349b1ec8c071":{
      "scriptId":"u68"}}});