$axure.loadCurrentPage({
  "url":"卡券_-_已支付.html",
  "generationDate":new Date(1463988222919.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7369f5a9f06e4c7cbc257304ec719b77",
    "type":"Axure:Page",
    "name":"卡券 - 已支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c5fc33e7e934b0b9ff94c3a7ac4b341",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":960},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdd880e4d014799b050c31f888cbc00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":960},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_已支付/u0.png"}},
{
          "id":"af45471b9feb4687afe7be8d9c81926f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f1b7c2e66e14771920c7874ec947c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"a7c98490dfb34192b5771bb2cee4ee3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae619f2fb6ed479c8a45e51852f1fda7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"dc8bd02583cf49bcb90cfa5d25f78c63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb78e1ddacd84f8a8b98b012b22bee5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"0a8b687dbae8419382e7e5418a7243d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":360,
              "height":263},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a47a2b541d473a9fe5341d7805a7a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":360,
                  "height":263},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u2.png"}},
{
          "id":"82333b4a7db141d4a494ff554c6dedce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":335},
            "size":{
              "width":340,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d771ef64272341719bdd38ef02e9616c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":335},
                "size":{
                  "width":340,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u8.png"}},
{
          "id":"78d25b841eaa4db1899444ccb793fac4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":309},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087fd071e4734954a7ae6a7fafb98abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":309},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3377d77bff9f4eae94f87dbf9ff180ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":360,
              "height":153},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b5fc32fe53d427c82076dccf4411b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":360,
                  "height":153},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u16.png"}},
{
          "id":"76d28b982d614e69b4958e81ec3c6ac6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":177},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"bd99678f093543b6986fbf0aee2f13b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":149},
            "size":{
              "width":58,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8db644d9a144b392a0370fcba7543d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":149},
                "size":{
                  "width":58,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u15.png"}},
{
          "id":"bfaf4178c0cf4988b6b1f8fcb570159a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":154},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af32ab47c26349f7b25207fd41bdbc35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":154},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f28626d917454698907ee645cc4f6d1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":191},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d4d206242c432682567b964eb31423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":191},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u19.png"}},
{
          "id":"534b8cf3ecf34560a90cff6753f27702",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":73,
              "y":195},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5815a073f8644252b871cde6a0d38e50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":73,
                  "y":195},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5ad6f72fc71457bb6582cd547960379",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":245},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"89dfcaa775d4463aa28c0da2cb7a00a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":195},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5cf93e402e412fb6b6ebcc7d2c6194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":195},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"662c4f0e3eac409ca9ead11b1eadf71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":15,
              "y":263},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7cc6707191e403f8f3db18c2977d03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":263},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2bbf433c0724b3ab26f71feff066022",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":225},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85e9579936dd4a19935649b7a2a37cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":225},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"534cec736d69489c8319ad2b42a11e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":108},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c00a6f585af24da5836ba5c17d2faf69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":108},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3f8bd7f2e87402682dbdaaf47cb5a05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":402},
            "size":{
              "width":360,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08567690d6a04a59815401bebeb2d16c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":360,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u36.png"}},
{
          "id":"a051c1531f704252bbbeab755bd12258",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":418},
            "size":{
              "width":117,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"653713864ccb42b4850288897e284d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":418},
                "size":{
                  "width":117,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"843bd20dffe34fa0b266151eb7772381",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":440},
            "size":{
              "width":165,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f57b513971472198b9c72a7f06ed4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":440},
                "size":{
                  "width":165,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d712f35e473459598ce00774c688ece",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":461},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5a090055d6f4d0c84c0ed07ace2e0a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":461},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c7b46706a0f4f35a324316d5c55297e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":895},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668ec8e5844849a299b93482978761df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":895},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"0025832af97940cbb1515bb25c4d1beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":911},
            "size":{
              "width":180,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6b1192ee0543c0b63a08e673f2219a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":911},
                "size":{
                  "width":180,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6510cac362144fba2924d6caf6b1250",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":906},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58332e1105f94a4eba42e1ed0d4f5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":906},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_已支付/u46.png"}},
{
          "id":"26f0810762394354b3c00e28ce1c271e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":498},
            "size":{
              "width":360,
              "height":392},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"953e9e36cc8040dbb5d068f0db7e907e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":498},
                "size":{
                  "width":360,
                  "height":392},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券_-_已支付/u48.png"}},
{
          "id":"b0d6d62010d044f68de4986dbf35eed4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":511},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df3b6883911849e38ada7db4e7a405ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":511},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b832642bcf44adbb34fbe246e0421fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":22,
              "y":537},
            "size":{
              "width":322,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ec1fdda91549669f0ab0565173ab31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":22,
                  "y":537},
                "size":{
                  "width":322,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3f82428a8864590926928864ea6ab2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":649},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582df51e8a264950a9a09a1d29a10095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":649},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29423797edc246adb069d9d04194aa70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":779},
            "size":{
              "width":340,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e66e2eff366145f9afcc34e4229055c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":779},
                "size":{
                  "width":340,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券详情/u39.png"}},
{
          "id":"162da2facc504458aef432f227fff04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":789},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a8bdb91a9484535bd37aa96eb8236c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":789},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d054986593a64a448bddb7eaf3281a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":62,
              "y":813},
            "size":{
              "width":274,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb07bc137d049ab831fd2a1189d61fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":62,
                  "y":813},
                "size":{
                  "width":274,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467ceaf4421a451cbb631db6b293a394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":789},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de751b5c62a4561b3e1176e6e113640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":789},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7396117620a542c888383893bd225b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":813},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a707a8eab84e2cbc5d94a7ab5ea1d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":813},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e897b5754021479389024c222c7840e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":857},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f030cea223944f2c8bdc4dda39c3b14f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":857},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a6e6972298844ceaff4b40fbff61612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":857},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffecbb0f411e4599961a5fa2859645b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":857},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5911e689e7284f89b520212049683bb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":669},
            "size":{
              "width":340,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105d12fda5bc4298acd07b2a001f5de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":669},
                "size":{
                  "width":340,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券详情/u39.png"}},
{
          "id":"0700d291f336479eaa9dfebb37444f7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":679},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8912c426a04cebbbd50ae3278afed5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":679},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d04a2caa9be4f26913de4bde7b025a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":62,
              "y":703},
            "size":{
              "width":209,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b58fb8d8114632b9ca7b51fa5c2d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":62,
                  "y":703},
                "size":{
                  "width":209,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0aed737d23644ad8dbb56739154a53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":679},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0887eafa5a4ca4b48dd5159a4d4b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":679},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54648264095244348e04723af19c0177",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":703},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e361df24569b49bfbd16dd77b845b0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":703},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e6b78505a21407ba646719a0c509b68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":747},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c070def710c547b4bf034e66ef6445bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":747},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01f3210ef6e44fde95d9d5215b24abae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":747},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"588a7e79cc054c678a42d9139dc49684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":747},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bae42f4dbc147f59593e66b343fa40b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":914},
            "size":{
              "width":50,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/卡券详情/u85_end.png",
            "line~":"images/卡券_-_已支付/u84_line.png"}},
{
          "id":"49063dc320c44a9e9e878c7aa33c7af5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":388,
              "y":911},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d90250d8a0994d098879c58ca13763c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":388,
                  "y":911},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3844e70f0bed473eb29957f3e3c86135",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":111},
            "size":{
              "width":343,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/确认订单/u53_end.png",
            "line~":"images/支付成功/u46_line.png"}},
{
          "id":"d51ef5bd1f94486498571f123f2682eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":411,
              "y":107},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"968e8c6d4bfe45f183fa8118a0ff0f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":411,
                  "y":107},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c5fc33e7e934b0b9ff94c3a7ac4b341":{
      "scriptId":"u0"},
    "cfdd880e4d014799b050c31f888cbc00":{
      "scriptId":"u1"},
    "af45471b9feb4687afe7be8d9c81926f":{
      "scriptId":"u2"},
    "3f1b7c2e66e14771920c7874ec947c3b":{
      "scriptId":"u3"},
    "a7c98490dfb34192b5771bb2cee4ee3e":{
      "scriptId":"u4"},
    "ae619f2fb6ed479c8a45e51852f1fda7":{
      "scriptId":"u5"},
    "dc8bd02583cf49bcb90cfa5d25f78c63":{
      "scriptId":"u6"},
    "bb78e1ddacd84f8a8b98b012b22bee5a":{
      "scriptId":"u7"},
    "0a8b687dbae8419382e7e5418a7243d3":{
      "scriptId":"u8"},
    "39a47a2b541d473a9fe5341d7805a7a1":{
      "scriptId":"u9"},
    "82333b4a7db141d4a494ff554c6dedce":{
      "scriptId":"u10"},
    "d771ef64272341719bdd38ef02e9616c":{
      "scriptId":"u11"},
    "78d25b841eaa4db1899444ccb793fac4":{
      "scriptId":"u12"},
    "087fd071e4734954a7ae6a7fafb98abf":{
      "scriptId":"u13"},
    "3377d77bff9f4eae94f87dbf9ff180ed":{
      "scriptId":"u14"},
    "4b5fc32fe53d427c82076dccf4411b30":{
      "scriptId":"u15"},
    "76d28b982d614e69b4958e81ec3c6ac6":{
      "scriptId":"u16"},
    "bd99678f093543b6986fbf0aee2f13b7":{
      "scriptId":"u17"},
    "eb8db644d9a144b392a0370fcba7543d":{
      "scriptId":"u18"},
    "bfaf4178c0cf4988b6b1f8fcb570159a":{
      "scriptId":"u19"},
    "af32ab47c26349f7b25207fd41bdbc35":{
      "scriptId":"u20"},
    "f28626d917454698907ee645cc4f6d1c":{
      "scriptId":"u21"},
    "01d4d206242c432682567b964eb31423":{
      "scriptId":"u22"},
    "534b8cf3ecf34560a90cff6753f27702":{
      "scriptId":"u23"},
    "5815a073f8644252b871cde6a0d38e50":{
      "scriptId":"u24"},
    "e5ad6f72fc71457bb6582cd547960379":{
      "scriptId":"u25"},
    "89dfcaa775d4463aa28c0da2cb7a00a6":{
      "scriptId":"u26"},
    "5a5cf93e402e412fb6b6ebcc7d2c6194":{
      "scriptId":"u27"},
    "662c4f0e3eac409ca9ead11b1eadf71e":{
      "scriptId":"u28"},
    "a7cc6707191e403f8f3db18c2977d03e":{
      "scriptId":"u29"},
    "d2bbf433c0724b3ab26f71feff066022":{
      "scriptId":"u30"},
    "85e9579936dd4a19935649b7a2a37cf9":{
      "scriptId":"u31"},
    "534cec736d69489c8319ad2b42a11e0a":{
      "scriptId":"u32"},
    "c00a6f585af24da5836ba5c17d2faf69":{
      "scriptId":"u33"},
    "f3f8bd7f2e87402682dbdaaf47cb5a05":{
      "scriptId":"u34"},
    "08567690d6a04a59815401bebeb2d16c":{
      "scriptId":"u35"},
    "a051c1531f704252bbbeab755bd12258":{
      "scriptId":"u36"},
    "653713864ccb42b4850288897e284d5c":{
      "scriptId":"u37"},
    "843bd20dffe34fa0b266151eb7772381":{
      "scriptId":"u38"},
    "52f57b513971472198b9c72a7f06ed4b":{
      "scriptId":"u39"},
    "3d712f35e473459598ce00774c688ece":{
      "scriptId":"u40"},
    "a5a090055d6f4d0c84c0ed07ace2e0a3":{
      "scriptId":"u41"},
    "4c7b46706a0f4f35a324316d5c55297e":{
      "scriptId":"u42"},
    "668ec8e5844849a299b93482978761df":{
      "scriptId":"u43"},
    "0025832af97940cbb1515bb25c4d1beb":{
      "scriptId":"u44"},
    "bd6b1192ee0543c0b63a08e673f2219a":{
      "scriptId":"u45"},
    "d6510cac362144fba2924d6caf6b1250":{
      "scriptId":"u46"},
    "58332e1105f94a4eba42e1ed0d4f5247":{
      "scriptId":"u47"},
    "26f0810762394354b3c00e28ce1c271e":{
      "scriptId":"u48"},
    "953e9e36cc8040dbb5d068f0db7e907e":{
      "scriptId":"u49"},
    "b0d6d62010d044f68de4986dbf35eed4":{
      "scriptId":"u50"},
    "df3b6883911849e38ada7db4e7a405ff":{
      "scriptId":"u51"},
    "2b832642bcf44adbb34fbe246e0421fb":{
      "scriptId":"u52"},
    "d1ec1fdda91549669f0ab0565173ab31":{
      "scriptId":"u53"},
    "e3f82428a8864590926928864ea6ab2b":{
      "scriptId":"u54"},
    "582df51e8a264950a9a09a1d29a10095":{
      "scriptId":"u55"},
    "29423797edc246adb069d9d04194aa70":{
      "scriptId":"u56"},
    "e66e2eff366145f9afcc34e4229055c2":{
      "scriptId":"u57"},
    "162da2facc504458aef432f227fff04e":{
      "scriptId":"u58"},
    "4a8bdb91a9484535bd37aa96eb8236c5":{
      "scriptId":"u59"},
    "d054986593a64a448bddb7eaf3281a95":{
      "scriptId":"u60"},
    "fcb07bc137d049ab831fd2a1189d61fb":{
      "scriptId":"u61"},
    "467ceaf4421a451cbb631db6b293a394":{
      "scriptId":"u62"},
    "5de751b5c62a4561b3e1176e6e113640":{
      "scriptId":"u63"},
    "7396117620a542c888383893bd225b76":{
      "scriptId":"u64"},
    "33a707a8eab84e2cbc5d94a7ab5ea1d8":{
      "scriptId":"u65"},
    "e897b5754021479389024c222c7840e3":{
      "scriptId":"u66"},
    "f030cea223944f2c8bdc4dda39c3b14f":{
      "scriptId":"u67"},
    "0a6e6972298844ceaff4b40fbff61612":{
      "scriptId":"u68"},
    "ffecbb0f411e4599961a5fa2859645b8":{
      "scriptId":"u69"},
    "5911e689e7284f89b520212049683bb2":{
      "scriptId":"u70"},
    "105d12fda5bc4298acd07b2a001f5de9":{
      "scriptId":"u71"},
    "0700d291f336479eaa9dfebb37444f7d":{
      "scriptId":"u72"},
    "7a8912c426a04cebbbd50ae3278afed5":{
      "scriptId":"u73"},
    "1d04a2caa9be4f26913de4bde7b025a4":{
      "scriptId":"u74"},
    "56b58fb8d8114632b9ca7b51fa5c2d86":{
      "scriptId":"u75"},
    "d0aed737d23644ad8dbb56739154a53d":{
      "scriptId":"u76"},
    "fe0887eafa5a4ca4b48dd5159a4d4b0a":{
      "scriptId":"u77"},
    "54648264095244348e04723af19c0177":{
      "scriptId":"u78"},
    "e361df24569b49bfbd16dd77b845b0b7":{
      "scriptId":"u79"},
    "0e6b78505a21407ba646719a0c509b68":{
      "scriptId":"u80"},
    "c070def710c547b4bf034e66ef6445bb":{
      "scriptId":"u81"},
    "01f3210ef6e44fde95d9d5215b24abae":{
      "scriptId":"u82"},
    "588a7e79cc054c678a42d9139dc49684":{
      "scriptId":"u83"},
    "6bae42f4dbc147f59593e66b343fa40b":{
      "scriptId":"u84"},
    "49063dc320c44a9e9e878c7aa33c7af5":{
      "scriptId":"u85"},
    "d90250d8a0994d098879c58ca13763c6":{
      "scriptId":"u86"},
    "3844e70f0bed473eb29957f3e3c86135":{
      "scriptId":"u87"},
    "d51ef5bd1f94486498571f123f2682eb":{
      "scriptId":"u88"},
    "968e8c6d4bfe45f183fa8118a0ff0f31":{
      "scriptId":"u89"}}});