$axure.loadCurrentPage({
  "url":"支付_1.html",
  "generationDate":new Date(1463988220048.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08ec552b0ad748be9a094c57d158001f",
    "type":"Axure:Page",
    "name":"支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b8aa406a32446af9347b8604954a1ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"745213a74ad54f398919aca7c926f50a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"e0a0d064653940dda8fc961ae0c02bf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a469903d4c429eac2fcba483d2be89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"a5cb98fe05fd47b7bebf633cd561a9cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08d65b373c74f9fa0d9123dcf1af8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"9c0aae214f034a55a4a1c64c5e50a16c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5de8d3daba84ff9a40aaf68c1649ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 确认订单（发票模块流程）",
                      "target":{
                        "targetType":"page",
                        "url":"确认订单（发票模块流程）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"e46d0c7b920948fc8b6c62474475e600",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":360,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88d9b7edecbf400bb2abb38191640c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":360,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u6.png"}},
{
          "id":"29307b71aea24581acecc0da9d63bfad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":111},
            "size":{
              "width":94,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f4a41258b534a43ae1b1eea388584e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":111},
                "size":{
                  "width":94,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"697696b9fa4648a2a439f637021eb160",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":360,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1fe0d518b1478f873d1bd02dcfa879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":360,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付/u22.png"}},
{
          "id":"a3c3f5dc5b3244ac97a07d41707b8fc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":254},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eeefa574370493fafc8fff9e740d726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":254},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3f7b7287d6f4fefb5bac49c81121444",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":302},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e296d1d4a349979a876471bcf33130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":302},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"18b3cc6158e24fada478cf435652d3dc",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":333},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ffd5649c6f4c4c9061b81450c73451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":333},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"555f224871df4676865f77747598de50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":147},
            "size":{
              "width":360,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc96f357f7fc4670828c62ada75dcfa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":147},
                "size":{
                  "width":360,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付_1/u20.png"}},
{
          "id":"7016df1dd5ce47ffa2e8e64af28568d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":20,
              "y":162},
            "size":{
              "width":180,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fad4ecacaaf40288a52ed95350a23c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":20,
                  "y":162},
                "size":{
                  "width":180,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7a0ef7a10f24c989182c44283661ef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":20,
              "y":184},
            "size":{
              "width":330,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a21d36f44484c5c89b49e90c5f79672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":20,
                  "y":184},
                "size":{
                  "width":330,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1ac0e20ffe64bd6889447476b8a8adb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":277},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u46_line.png"}},
{
          "id":"d12f9374d52f474abef0373d4c3a45f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":400},
            "size":{
              "width":330,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92af63ec88494ce28c752207517623c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":400},
                "size":{
                  "width":330,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付成功",
                      "target":{
                        "targetType":"page",
                        "url":"支付成功_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付_1/u27.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0b8aa406a32446af9347b8604954a1ad":{
      "scriptId":"u0"},
    "745213a74ad54f398919aca7c926f50a":{
      "scriptId":"u1"},
    "e0a0d064653940dda8fc961ae0c02bf5":{
      "scriptId":"u2"},
    "c6a469903d4c429eac2fcba483d2be89":{
      "scriptId":"u3"},
    "a5cb98fe05fd47b7bebf633cd561a9cd":{
      "scriptId":"u4"},
    "d08d65b373c74f9fa0d9123dcf1af8a4":{
      "scriptId":"u5"},
    "9c0aae214f034a55a4a1c64c5e50a16c":{
      "scriptId":"u6"},
    "f5de8d3daba84ff9a40aaf68c1649ee0":{
      "scriptId":"u7"},
    "e46d0c7b920948fc8b6c62474475e600":{
      "scriptId":"u8"},
    "88d9b7edecbf400bb2abb38191640c17":{
      "scriptId":"u9"},
    "29307b71aea24581acecc0da9d63bfad":{
      "scriptId":"u10"},
    "4f4a41258b534a43ae1b1eea388584e1":{
      "scriptId":"u11"},
    "697696b9fa4648a2a439f637021eb160":{
      "scriptId":"u12"},
    "4a1fe0d518b1478f873d1bd02dcfa879":{
      "scriptId":"u13"},
    "a3c3f5dc5b3244ac97a07d41707b8fc7":{
      "scriptId":"u14"},
    "0eeefa574370493fafc8fff9e740d726":{
      "scriptId":"u15"},
    "b3f7b7287d6f4fefb5bac49c81121444":{
      "scriptId":"u16"},
    "a4e296d1d4a349979a876471bcf33130":{
      "scriptId":"u17"},
    "18b3cc6158e24fada478cf435652d3dc":{
      "scriptId":"u18"},
    "70ffd5649c6f4c4c9061b81450c73451":{
      "scriptId":"u19"},
    "555f224871df4676865f77747598de50":{
      "scriptId":"u20"},
    "dc96f357f7fc4670828c62ada75dcfa6":{
      "scriptId":"u21"},
    "7016df1dd5ce47ffa2e8e64af28568d3":{
      "scriptId":"u22"},
    "3fad4ecacaaf40288a52ed95350a23c8":{
      "scriptId":"u23"},
    "d7a0ef7a10f24c989182c44283661ef7":{
      "scriptId":"u24"},
    "6a21d36f44484c5c89b49e90c5f79672":{
      "scriptId":"u25"},
    "c1ac0e20ffe64bd6889447476b8a8adb":{
      "scriptId":"u26"},
    "d12f9374d52f474abef0373d4c3a45f3":{
      "scriptId":"u27"},
    "92af63ec88494ce28c752207517623c7":{
      "scriptId":"u28"}}});