$axure.loadCurrentPage({
  "url":"支付成功_1.html",
  "generationDate":new Date(1463988220134.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d7df6dba92b44847acc62a8ccf76e68f",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0f40a6488aa447e6b8708c815245b6a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":644},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1612e2adaf89490c9109915c92c3bf2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":644},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功_1/u0.png"}},
{
          "id":"f897806b081d45bcb92125855cc90c78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a40ce5707543b6a85cbdbed66f41a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"8a56b3f8ee9f4e70a01cd530b627774b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e97e4094505242939a41b54a43c4a9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"bcd6fbc4bb6e4806ae77818d57cf0245",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5284d49372234712a37420dd046fe667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"2ea42400e31045ee9ef18b551404eefb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":360,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b0f4ccaecda4157a0b6e9d745559557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":360,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付_1/u20.png"}},
{
          "id":"a209f8a6a2f2459c95404ca2d026f660",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":20,
              "y":153},
            "size":{
              "width":180,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee17a41fedd4b3e9b333ac6e286fea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":20,
                  "y":153},
                "size":{
                  "width":180,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dbf29b383a94e4db72ace44097766c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":20,
              "y":175},
            "size":{
              "width":330,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b70df0cd394e6a981c94d30460f463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":20,
                  "y":175},
                "size":{
                  "width":330,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cec951f4057041cb89684d0df86d600f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":231},
            "size":{
              "width":360,
              "height":58},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b1a63680654baaa3d3005bc9e7ccd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":231},
                "size":{
                  "width":360,
                  "height":58},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功_1/u14.png"}},
{
          "id":"03f2cf76201341a4b006e0bd85dac545",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":19,
              "y":252},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da81d9a3d4f491f88803a9236621491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":252},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cace2cdf30bf4fd0bc2a2827eedc9f77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":107},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f3b9c650f9a422e843b27644c2bc815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":107},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c50d8c809c84f54a2c1a0410648386a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":410},
            "size":{
              "width":120,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51fc22c992254b29a3a91e3ca477f8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":410},
                "size":{
                  "width":120,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品 - 已支付",
                      "target":{
                        "targetType":"page",
                        "url":"商品_-_已支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功_1/u20.png"}},
{
          "id":"dc877205e7fd4232a795923927a3f7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":410},
            "size":{
              "width":120,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac99f183831943e0af827ff40d926007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":410},
                "size":{
                  "width":120,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功_1/u20.png"}},
{
          "id":"9280fff54879496ab4ff49ae445d4300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":288},
            "size":{
              "width":360,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a197d6e54624f1cac1f296ef2b21e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":288},
                "size":{
                  "width":360,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u36.png"}},
{
          "id":"6805cc4399754b14b95d553e54105dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":304},
            "size":{
              "width":117,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c5fe939912446aea9765896eef864df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":304},
                "size":{
                  "width":117,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a732552b38964ff0896219d079ba41ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":326},
            "size":{
              "width":165,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668ef3e56dde486aab150c7f68beb738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":326},
                "size":{
                  "width":165,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a230d272c0514d669f8218f93cb24951",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":347},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f584fe9916ff4d84b94498c6eb0b4abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":347},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97220b2653324a5ebb082744f22baddb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":111},
            "size":{
              "width":326,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/卡券详情/u85_end.png",
            "line~":"images/支付成功_1/u32_line.png"}},
{
          "id":"43760ea57be641c1b485bb288d5cf5af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":411,
              "y":107},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1001e4bdb1e4562b323caed1556dd60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":411,
                  "y":107},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0f40a6488aa447e6b8708c815245b6a3":{
      "scriptId":"u0"},
    "1612e2adaf89490c9109915c92c3bf2a":{
      "scriptId":"u1"},
    "f897806b081d45bcb92125855cc90c78":{
      "scriptId":"u2"},
    "b2a40ce5707543b6a85cbdbed66f41a2":{
      "scriptId":"u3"},
    "8a56b3f8ee9f4e70a01cd530b627774b":{
      "scriptId":"u4"},
    "e97e4094505242939a41b54a43c4a9bb":{
      "scriptId":"u5"},
    "bcd6fbc4bb6e4806ae77818d57cf0245":{
      "scriptId":"u6"},
    "5284d49372234712a37420dd046fe667":{
      "scriptId":"u7"},
    "2ea42400e31045ee9ef18b551404eefb":{
      "scriptId":"u8"},
    "6b0f4ccaecda4157a0b6e9d745559557":{
      "scriptId":"u9"},
    "a209f8a6a2f2459c95404ca2d026f660":{
      "scriptId":"u10"},
    "4ee17a41fedd4b3e9b333ac6e286fea8":{
      "scriptId":"u11"},
    "4dbf29b383a94e4db72ace44097766c0":{
      "scriptId":"u12"},
    "41b70df0cd394e6a981c94d30460f463":{
      "scriptId":"u13"},
    "cec951f4057041cb89684d0df86d600f":{
      "scriptId":"u14"},
    "70b1a63680654baaa3d3005bc9e7ccd8":{
      "scriptId":"u15"},
    "03f2cf76201341a4b006e0bd85dac545":{
      "scriptId":"u16"},
    "5da81d9a3d4f491f88803a9236621491":{
      "scriptId":"u17"},
    "cace2cdf30bf4fd0bc2a2827eedc9f77":{
      "scriptId":"u18"},
    "2f3b9c650f9a422e843b27644c2bc815":{
      "scriptId":"u19"},
    "8c50d8c809c84f54a2c1a0410648386a":{
      "scriptId":"u20"},
    "51fc22c992254b29a3a91e3ca477f8d6":{
      "scriptId":"u21"},
    "dc877205e7fd4232a795923927a3f7fb":{
      "scriptId":"u22"},
    "ac99f183831943e0af827ff40d926007":{
      "scriptId":"u23"},
    "9280fff54879496ab4ff49ae445d4300":{
      "scriptId":"u24"},
    "8a197d6e54624f1cac1f296ef2b21e48":{
      "scriptId":"u25"},
    "6805cc4399754b14b95d553e54105dac":{
      "scriptId":"u26"},
    "4c5fe939912446aea9765896eef864df":{
      "scriptId":"u27"},
    "a732552b38964ff0896219d079ba41ef":{
      "scriptId":"u28"},
    "668ef3e56dde486aab150c7f68beb738":{
      "scriptId":"u29"},
    "a230d272c0514d669f8218f93cb24951":{
      "scriptId":"u30"},
    "f584fe9916ff4d84b94498c6eb0b4abf":{
      "scriptId":"u31"},
    "97220b2653324a5ebb082744f22baddb":{
      "scriptId":"u32"},
    "43760ea57be641c1b485bb288d5cf5af":{
      "scriptId":"u33"},
    "d1001e4bdb1e4562b323caed1556dd60":{
      "scriptId":"u34"}}});