$axure.loadCurrentPage({
  "url":"物流详情.html",
  "generationDate":new Date(1463988224428.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fffbc4c7e00c484cbdc8d2dc983c947e",
    "type":"Axure:Page",
    "name":"物流详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69fece872bb149f896da12da260ce62c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":1130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8067389d16c4321acc0158d1acad7ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":1130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u0.png"}},
{
          "id":"18541e06cb6e4fd9a2f2c11fd0a014a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"929b96154a414dcfb34d1c3c2869e3d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"360785101936429385b80ff1f90565e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f829e1f81db486f8d5ef306921476a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"6ff705422ab645dc8b49397b2293951e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":57},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90f1271c1ef44bd39ba84b161a8ab990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":57},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品 - 已支付",
                      "target":{
                        "targetType":"page",
                        "url":"商品_-_已支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"48f479e39dfd43fe981ee525f1e704f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":360,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4414cb5fcb754f298a4de0f601603cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":360,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u8.png"}},
{
          "id":"bdcd914f235149079c051d49bec15fb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":102},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d1266f3d274424b74df36424057059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":102},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ad7fcd9e6234aeaa275929a4f70f4af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":124},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72154c46ded4584bb4c583525eb8e9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":124},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d8c88dd0a5d40ccad6d5430db53a9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":145},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72bbe9c7475647cb85362c44dd9b0c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":145},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc21dd96aeb84a67a5123e60a4858805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":74,
              "y":102},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9aab795a41c409fb7200ec9878ba163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":102},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1522f04d9c44bc29c2e32ce0339d77e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":74,
              "y":124},
            "size":{
              "width":85,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b0972e2f5984b098907c7846739f3c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":124},
                "size":{
                  "width":85,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4ba8b3ee10b49a99d0e8aba891fb046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":74,
              "y":146},
            "size":{
              "width":103,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a140bb88894425891bbca11d6241146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":146},
                "size":{
                  "width":103,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6be5d2e0099747be9615143e052f5d76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":175},
            "size":{
              "width":360,
              "height":595},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60ff10c94c4b41cc9644ba63e2939e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":175},
                "size":{
                  "width":360,
                  "height":595},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u22.png"}},
{
          "id":"1811de02225f4fd19aa5ebd79d78602d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":204},
            "size":{
              "width":10,
              "height":566},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/物流详情/u24_line.png"}},
{
          "id":"22c75dcf49f24e92ba6ab4c0ded652eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":682},
            "size":{
              "width":257,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975d0cf502e7421898995377e763e811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":682},
                "size":{
                  "width":257,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d8c0b7df22d45a2be695c3c738bc9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":624},
            "size":{
              "width":119,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c15d581658b74798a009b513cf403f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":624},
                "size":{
                  "width":119,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e22d57675fea49f3a4df8ab9ea0d39c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":565},
            "size":{
              "width":193,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bcb131895c74bb38a6dfec49c06d382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":565},
                "size":{
                  "width":193,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fa147facf9f4a67b2a98402fbbd838a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":507},
            "size":{
              "width":133,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3f4b862d4147b5825020ea46aa3937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":507},
                "size":{
                  "width":133,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2c30f6a4a6549a88b0b79bc9bc1bd74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":448},
            "size":{
              "width":119,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3340c6a4ae774ffd8cf03974b4591b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":448},
                "size":{
                  "width":119,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2095b0fc8494a63b8f4db3f2266579b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":390},
            "size":{
              "width":119,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cd24af976c14cb49eeebf69bfc01ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":390},
                "size":{
                  "width":119,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1f98a3822e742609c1e1af359df1b2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":332},
            "size":{
              "width":163,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c0a24064685478c99ef9cb0a0cf3b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":332},
                "size":{
                  "width":163,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1090ff40e00741aba35634f39951c8de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":253},
            "size":{
              "width":257,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d24b215d3ae4eccae2a035bba237162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":253},
                "size":{
                  "width":257,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ea5fb1a3bc64246be10b48584983a8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":61,
              "y":195},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23134ffb15ab4fd8867269ba4f3aac48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":61,
                  "y":195},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"783f5777f6b948d49b8cf16a4dfb92d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":682},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eefa328295f4e8081a860f7aedb833d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":682},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"d6b8884c294245d2bececb7142ac0400",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":624},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a5049b6f0e4dc580ad63e1838d1105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":624},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"824f13b9676a4c42bc5aa7d69a830334",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":565},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da493a5ddf934bf2949d9809ea642351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":565},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"fa3a25438d1741139e905707bbbbce38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":507},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ea1dfc391014df39b032fa3be55e943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":507},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"02d4f16876844a0baaaa8c29b29858db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":448},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb7ff266ae545fd8a0df9a7d6f38e42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":448},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"1081526be6ad450c876464f581844309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":390},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc21609704f04843a4ed75a9e134c858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":390},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"0babe67c7f3b41f6b5699f5f8cd306b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":332},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ef601ec9e24f89a8cf60f69c460836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":332},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"ca0091ad7bd44469afcf716dc8092e90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":25,
              "y":253},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"542aa3e3ffae48af947890086963f03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":25,
                  "y":253},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u43.png"}},
{
          "id":"0076e17517cf4e42b7b9f9e6b5e079c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF008000},
            "location":{
              "x":25,
              "y":195},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd8c1006c664c9b99efcb6d3c5d9a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF008000},
                "location":{
                  "x":25,
                  "y":195},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u59.png"}},
{
          "id":"0be33e8d53034fb48856ea6324723fee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":791},
            "size":{
              "width":110,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/物流详情/u61_line.png"}},
{
          "id":"b93c2f5cc45c4a60a7dbf540de1234bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":791},
            "size":{
              "width":110,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/物流详情/u61_line.png"}},
{
          "id":"aeda7efd5cbd41869af3a58f1b25e53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":137,
              "y":784},
            "size":{
              "width":20,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f282d27ae2b46ab92ddf3a33832d93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":784},
                "size":{
                  "width":20,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b979049500e4776a5d49f482b646c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":157,
              "y":788},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab791762abdf480897cbc9a1083067b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":788},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ea8a78879349ad8d306057668b62a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":818},
            "size":{
              "width":178,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f3d6c5afbb4269ad8d2bea406f373f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":818},
                "size":{
                  "width":178,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u67.png"}},
{
          "id":"b4cf9cafa63b4e1380be97008e6e44d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":818},
            "size":{
              "width":178,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6cf72cfcd4427fb7a22335d8975c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":818},
                "size":{
                  "width":178,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u67.png"}},
{
          "id":"d03de4b2b965481ebde052d984aae3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":902},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5da83becd6942908fb3d35108ea15d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":902},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"927298a598544487b87eb70f9f078906",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":9,
              "y":828},
            "size":{
              "width":160,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f227531316d480290aac71661db81a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":9,
                  "y":828},
                "size":{
                  "width":160,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品详情",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"822ba62a9af94ec7b19891a057fea76b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":192,
              "y":828},
            "size":{
              "width":160,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b230ff5761e418a8c7e57169f57873f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":192,
                  "y":828},
                "size":{
                  "width":160,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卡券详情",
                      "target":{
                        "targetType":"page",
                        "url":"卡券详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"61b7bb1e429140eeac2184639a12266c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":902},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f2e7f9fc3c4efa9cb030adca7e5096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":902},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6d53903028f44bcb449d0f2470a0ecb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":928},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97d722238f654a4493ea6928b73190b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":928},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"794444ed970c46f396b99a2473697fa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":928},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc38777f3e94c8d8bf72ce6afdec7aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":928},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e618aba182d48b098194e69d06c2dcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":958},
            "size":{
              "width":178,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78ccd575a7f4b839d47960db63a4d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":958},
                "size":{
                  "width":178,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u67.png"}},
{
          "id":"7d9c8f6cc06545968cd0b1f1f373d122",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":958},
            "size":{
              "width":178,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a9cbf5badee407fa38662039248ec91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":958},
                "size":{
                  "width":178,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流详情/u67.png"}},
{
          "id":"5903458797324ac0aa11a03894b01c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1042},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cdfac0b04d4396a5b9b4f029df23f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1042},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7804e64d2274af492ba0d712108f842",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":9,
              "y":968},
            "size":{
              "width":160,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fed67d4e63ba4c809a51af4ea4492db0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":9,
                  "y":968},
                "size":{
                  "width":160,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卡券详情",
                      "target":{
                        "targetType":"page",
                        "url":"卡券详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"368fa5087f1749a88f8424feb45669c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":192,
              "y":968},
            "size":{
              "width":160,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"766ae7bb846f4d0496051df06f15c718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":192,
                  "y":968},
                "size":{
                  "width":160,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卡券详情",
                      "target":{
                        "targetType":"page",
                        "url":"卡券详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"79eedf58461a4a318785f791237c8be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":1042},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e16c74d90e9e4d7baef5ce3c7eb07f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":1042},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"627784ef0e2b49ffa94101ebe0071124",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":1068},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ccd570aedd48d1a9134efc92ba33ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":1068},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a524fe65145948e580feb68c90bd37e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":1068},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47afdac315474a41aefc3ca084c4fff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":1068},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "69fece872bb149f896da12da260ce62c":{
      "scriptId":"u0"},
    "d8067389d16c4321acc0158d1acad7ba":{
      "scriptId":"u1"},
    "18541e06cb6e4fd9a2f2c11fd0a014a0":{
      "scriptId":"u2"},
    "929b96154a414dcfb34d1c3c2869e3d4":{
      "scriptId":"u3"},
    "360785101936429385b80ff1f90565e7":{
      "scriptId":"u4"},
    "3f829e1f81db486f8d5ef306921476a7":{
      "scriptId":"u5"},
    "6ff705422ab645dc8b49397b2293951e":{
      "scriptId":"u6"},
    "90f1271c1ef44bd39ba84b161a8ab990":{
      "scriptId":"u7"},
    "48f479e39dfd43fe981ee525f1e704f6":{
      "scriptId":"u8"},
    "4414cb5fcb754f298a4de0f601603cf2":{
      "scriptId":"u9"},
    "bdcd914f235149079c051d49bec15fb9":{
      "scriptId":"u10"},
    "91d1266f3d274424b74df36424057059":{
      "scriptId":"u11"},
    "1ad7fcd9e6234aeaa275929a4f70f4af":{
      "scriptId":"u12"},
    "e72154c46ded4584bb4c583525eb8e9e":{
      "scriptId":"u13"},
    "3d8c88dd0a5d40ccad6d5430db53a9b3":{
      "scriptId":"u14"},
    "72bbe9c7475647cb85362c44dd9b0c07":{
      "scriptId":"u15"},
    "cc21dd96aeb84a67a5123e60a4858805":{
      "scriptId":"u16"},
    "f9aab795a41c409fb7200ec9878ba163":{
      "scriptId":"u17"},
    "b1522f04d9c44bc29c2e32ce0339d77e":{
      "scriptId":"u18"},
    "2b0972e2f5984b098907c7846739f3c4":{
      "scriptId":"u19"},
    "c4ba8b3ee10b49a99d0e8aba891fb046":{
      "scriptId":"u20"},
    "0a140bb88894425891bbca11d6241146":{
      "scriptId":"u21"},
    "6be5d2e0099747be9615143e052f5d76":{
      "scriptId":"u22"},
    "60ff10c94c4b41cc9644ba63e2939e31":{
      "scriptId":"u23"},
    "1811de02225f4fd19aa5ebd79d78602d":{
      "scriptId":"u24"},
    "22c75dcf49f24e92ba6ab4c0ded652eb":{
      "scriptId":"u25"},
    "975d0cf502e7421898995377e763e811":{
      "scriptId":"u26"},
    "7d8c0b7df22d45a2be695c3c738bc9ec":{
      "scriptId":"u27"},
    "c15d581658b74798a009b513cf403f37":{
      "scriptId":"u28"},
    "e22d57675fea49f3a4df8ab9ea0d39c8":{
      "scriptId":"u29"},
    "2bcb131895c74bb38a6dfec49c06d382":{
      "scriptId":"u30"},
    "1fa147facf9f4a67b2a98402fbbd838a":{
      "scriptId":"u31"},
    "cc3f4b862d4147b5825020ea46aa3937":{
      "scriptId":"u32"},
    "a2c30f6a4a6549a88b0b79bc9bc1bd74":{
      "scriptId":"u33"},
    "3340c6a4ae774ffd8cf03974b4591b62":{
      "scriptId":"u34"},
    "c2095b0fc8494a63b8f4db3f2266579b":{
      "scriptId":"u35"},
    "7cd24af976c14cb49eeebf69bfc01ed9":{
      "scriptId":"u36"},
    "f1f98a3822e742609c1e1af359df1b2b":{
      "scriptId":"u37"},
    "3c0a24064685478c99ef9cb0a0cf3b36":{
      "scriptId":"u38"},
    "1090ff40e00741aba35634f39951c8de":{
      "scriptId":"u39"},
    "8d24b215d3ae4eccae2a035bba237162":{
      "scriptId":"u40"},
    "4ea5fb1a3bc64246be10b48584983a8a":{
      "scriptId":"u41"},
    "23134ffb15ab4fd8867269ba4f3aac48":{
      "scriptId":"u42"},
    "783f5777f6b948d49b8cf16a4dfb92d7":{
      "scriptId":"u43"},
    "2eefa328295f4e8081a860f7aedb833d":{
      "scriptId":"u44"},
    "d6b8884c294245d2bececb7142ac0400":{
      "scriptId":"u45"},
    "17a5049b6f0e4dc580ad63e1838d1105":{
      "scriptId":"u46"},
    "824f13b9676a4c42bc5aa7d69a830334":{
      "scriptId":"u47"},
    "da493a5ddf934bf2949d9809ea642351":{
      "scriptId":"u48"},
    "fa3a25438d1741139e905707bbbbce38":{
      "scriptId":"u49"},
    "6ea1dfc391014df39b032fa3be55e943":{
      "scriptId":"u50"},
    "02d4f16876844a0baaaa8c29b29858db":{
      "scriptId":"u51"},
    "9fb7ff266ae545fd8a0df9a7d6f38e42":{
      "scriptId":"u52"},
    "1081526be6ad450c876464f581844309":{
      "scriptId":"u53"},
    "dc21609704f04843a4ed75a9e134c858":{
      "scriptId":"u54"},
    "0babe67c7f3b41f6b5699f5f8cd306b4":{
      "scriptId":"u55"},
    "67ef601ec9e24f89a8cf60f69c460836":{
      "scriptId":"u56"},
    "ca0091ad7bd44469afcf716dc8092e90":{
      "scriptId":"u57"},
    "542aa3e3ffae48af947890086963f03e":{
      "scriptId":"u58"},
    "0076e17517cf4e42b7b9f9e6b5e079c2":{
      "scriptId":"u59"},
    "ffd8c1006c664c9b99efcb6d3c5d9a3b":{
      "scriptId":"u60"},
    "0be33e8d53034fb48856ea6324723fee":{
      "scriptId":"u61"},
    "b93c2f5cc45c4a60a7dbf540de1234bd":{
      "scriptId":"u62"},
    "aeda7efd5cbd41869af3a58f1b25e53d":{
      "scriptId":"u63"},
    "7f282d27ae2b46ab92ddf3a33832d93c":{
      "scriptId":"u64"},
    "4b979049500e4776a5d49f482b646c87":{
      "scriptId":"u65"},
    "ab791762abdf480897cbc9a1083067b5":{
      "scriptId":"u66"},
    "52ea8a78879349ad8d306057668b62a2":{
      "scriptId":"u67"},
    "a6f3d6c5afbb4269ad8d2bea406f373f":{
      "scriptId":"u68"},
    "b4cf9cafa63b4e1380be97008e6e44d5":{
      "scriptId":"u69"},
    "cf6cf72cfcd4427fb7a22335d8975c9e":{
      "scriptId":"u70"},
    "d03de4b2b965481ebde052d984aae3b1":{
      "scriptId":"u71"},
    "a5da83becd6942908fb3d35108ea15d0":{
      "scriptId":"u72"},
    "927298a598544487b87eb70f9f078906":{
      "scriptId":"u73"},
    "7f227531316d480290aac71661db81a4":{
      "scriptId":"u74"},
    "822ba62a9af94ec7b19891a057fea76b":{
      "scriptId":"u75"},
    "5b230ff5761e418a8c7e57169f57873f":{
      "scriptId":"u76"},
    "61b7bb1e429140eeac2184639a12266c":{
      "scriptId":"u77"},
    "85f2e7f9fc3c4efa9cb030adca7e5096":{
      "scriptId":"u78"},
    "a6d53903028f44bcb449d0f2470a0ecb":{
      "scriptId":"u79"},
    "97d722238f654a4493ea6928b73190b7":{
      "scriptId":"u80"},
    "794444ed970c46f396b99a2473697fa4":{
      "scriptId":"u81"},
    "7cc38777f3e94c8d8bf72ce6afdec7aa":{
      "scriptId":"u82"},
    "6e618aba182d48b098194e69d06c2dcc":{
      "scriptId":"u83"},
    "a78ccd575a7f4b839d47960db63a4d96":{
      "scriptId":"u84"},
    "7d9c8f6cc06545968cd0b1f1f373d122":{
      "scriptId":"u85"},
    "6a9cbf5badee407fa38662039248ec91":{
      "scriptId":"u86"},
    "5903458797324ac0aa11a03894b01c69":{
      "scriptId":"u87"},
    "32cdfac0b04d4396a5b9b4f029df23f8":{
      "scriptId":"u88"},
    "e7804e64d2274af492ba0d712108f842":{
      "scriptId":"u89"},
    "fed67d4e63ba4c809a51af4ea4492db0":{
      "scriptId":"u90"},
    "368fa5087f1749a88f8424feb45669c4":{
      "scriptId":"u91"},
    "766ae7bb846f4d0496051df06f15c718":{
      "scriptId":"u92"},
    "79eedf58461a4a318785f791237c8be8":{
      "scriptId":"u93"},
    "e16c74d90e9e4d7baef5ce3c7eb07f5e":{
      "scriptId":"u94"},
    "627784ef0e2b49ffa94101ebe0071124":{
      "scriptId":"u95"},
    "70ccd570aedd48d1a9134efc92ba33ee":{
      "scriptId":"u96"},
    "a524fe65145948e580feb68c90bd37e5":{
      "scriptId":"u97"},
    "47afdac315474a41aefc3ca084c4fff1":{
      "scriptId":"u98"}}});