$axure.loadCurrentPage({
  "url":"支付成功.html",
  "generationDate":new Date(1463988217999.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"68ab8931ecca403292bb2ab6bece67b6",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0acf37dbe0e04de6bb887ebf38deb881",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":360,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf92054b53d24cdb8baf953d9fa71860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":360,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"3d99415507a7464199db05f5981a2272",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":360,
              "height":263},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aad5836d4f79412280551aea1adbbd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":360,
                  "height":263},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u2.png"}},
{
          "id":"ce145fb2d36142cfb86f38694731bb56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f4f3aa546a41859b97e16cf7019715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"d0f9e6f750c8401e8003a6c560ff197f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":56},
            "size":{
              "width":360,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db2890bad87c40aea878b54b92d62644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":360,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"8bec6d3d1b8545a28e09b2204512a38d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":335},
            "size":{
              "width":340,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38f76f62d4c44ceb499d2fb02c581bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":335},
                "size":{
                  "width":340,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u8.png"}},
{
          "id":"2547ce0bcb8a4012b995125db44d016f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":309},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca40c52184aa4d82857d4346e9921db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":309},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d106a479ece402ea5ed9652d3f85b05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "location":{
              "x":203,
              "y":513},
            "size":{
              "width":130,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eec551ee1d64d9f98c30bf524689f03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "location":{
                  "x":203,
                  "y":513},
                "size":{
                  "width":130,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功/u12.png",
            "mouseOver~":"images/支付成功/u12.png"}},
{
          "id":"74d63fdbaae449628d035a92bb4d0d84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":58},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dde293d826ca4a7eb9203ff4fd6ba593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":58},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/卡券详情/u83.png"}},
{
          "id":"8ac19edebb66478d8ea97079ca3f505f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":360,
              "height":153},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aad3d761f7b47ee8bbdb04a5bfe941a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":360,
                  "height":153},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u16.png"}},
{
          "id":"b63382493a54426cb7742ad8ec61e5fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":177},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"44486185d8e44c1295bcdc4cec29e8fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":149},
            "size":{
              "width":58,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459f51d9969b4314b28216c55fca78a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":149},
                "size":{
                  "width":58,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u15.png"}},
{
          "id":"e496b5fdf40642a9b87121a8cb9795b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":154},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32780ebbd25c434d80a97cf9717fd2b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":154},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78c39305bbc44912a73d723eab542293",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":191},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d87b8d711a47cface836a8cd80e836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":191},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u19.png"}},
{
          "id":"1ee627c580ab47c9a9aea49c64b8f64d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":73,
              "y":195},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cdb12083d14cc1af32344241901c6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":73,
                  "y":195},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc29560df5f245c2811875c9533988a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":245},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/确认订单/u14_line.png"}},
{
          "id":"9d101934c6de44f6a6408bf77462ba06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":195},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32b3f0c2c034de8a774ffa775803bef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":195},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98a1d68adce544d6a0f16bc71c16f0c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":15,
              "y":263},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abbb98eed2414a5a9a859d123046a980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":263},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7f2b01198ef46dea6c04917643d12bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":229},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d13a9ada5bbd414f93e08f2a95436474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":229},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6dd6e7c523d745ceaca3a12ef792542c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":108},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a6077ef92045cd9c15dd08b941e72f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":108},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35e56f7813af4f2cb5aa2700b4e561c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":402},
            "size":{
              "width":360,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c41a0cf1ea6416f9de47b4a1150932a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":360,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u36.png"}},
{
          "id":"c62a4fe791594696a4c765f6d4b9446b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":418},
            "size":{
              "width":117,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6060b8ceca49f5ba97f22a2dc0d7e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":418},
                "size":{
                  "width":117,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3209bbd6dc784a149f415a5179a52a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":440},
            "size":{
              "width":165,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6a954599c434af7a34e37762b70e5f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":440},
                "size":{
                  "width":165,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"068ae181c38d4703a4d27d37c0c6bdc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":15,
              "y":461},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca21f5cc33634c65af356371149d457a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":461},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"827db3e83c344734a82bde86ec98ced4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}}},
            "location":{
              "x":33,
              "y":513},
            "size":{
              "width":130,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e08ea88020451ca8d748194707f4f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}}},
                "location":{
                  "x":33,
                  "y":513},
                "size":{
                  "width":130,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卡券 - 已支付",
                      "target":{
                        "targetType":"page",
                        "url":"卡券_-_已支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功/u12.png",
            "mouseOver~":"images/支付成功/u12.png"}},
{
          "id":"6d83d1053f13444eb262305f35c4475c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":111},
            "size":{
              "width":343,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/确认订单/u53_end.png",
            "line~":"images/支付成功/u46_line.png"}},
{
          "id":"cf1bd7a5e6e0498f802f5021bf93c191",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":411,
              "y":107},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9207f0467d4841a544a78e2193b837",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":411,
                  "y":107},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0acf37dbe0e04de6bb887ebf38deb881":{
      "scriptId":"u0"},
    "bf92054b53d24cdb8baf953d9fa71860":{
      "scriptId":"u1"},
    "3d99415507a7464199db05f5981a2272":{
      "scriptId":"u2"},
    "aad5836d4f79412280551aea1adbbd18":{
      "scriptId":"u3"},
    "ce145fb2d36142cfb86f38694731bb56":{
      "scriptId":"u4"},
    "b2f4f3aa546a41859b97e16cf7019715":{
      "scriptId":"u5"},
    "d0f9e6f750c8401e8003a6c560ff197f":{
      "scriptId":"u6"},
    "db2890bad87c40aea878b54b92d62644":{
      "scriptId":"u7"},
    "8bec6d3d1b8545a28e09b2204512a38d":{
      "scriptId":"u8"},
    "c38f76f62d4c44ceb499d2fb02c581bb":{
      "scriptId":"u9"},
    "2547ce0bcb8a4012b995125db44d016f":{
      "scriptId":"u10"},
    "ca40c52184aa4d82857d4346e9921db7":{
      "scriptId":"u11"},
    "8d106a479ece402ea5ed9652d3f85b05":{
      "scriptId":"u12"},
    "1eec551ee1d64d9f98c30bf524689f03":{
      "scriptId":"u13"},
    "74d63fdbaae449628d035a92bb4d0d84":{
      "scriptId":"u14"},
    "dde293d826ca4a7eb9203ff4fd6ba593":{
      "scriptId":"u15"},
    "8ac19edebb66478d8ea97079ca3f505f":{
      "scriptId":"u16"},
    "3aad3d761f7b47ee8bbdb04a5bfe941a":{
      "scriptId":"u17"},
    "b63382493a54426cb7742ad8ec61e5fd":{
      "scriptId":"u18"},
    "44486185d8e44c1295bcdc4cec29e8fe":{
      "scriptId":"u19"},
    "459f51d9969b4314b28216c55fca78a2":{
      "scriptId":"u20"},
    "e496b5fdf40642a9b87121a8cb9795b4":{
      "scriptId":"u21"},
    "32780ebbd25c434d80a97cf9717fd2b5":{
      "scriptId":"u22"},
    "78c39305bbc44912a73d723eab542293":{
      "scriptId":"u23"},
    "62d87b8d711a47cface836a8cd80e836":{
      "scriptId":"u24"},
    "1ee627c580ab47c9a9aea49c64b8f64d":{
      "scriptId":"u25"},
    "95cdb12083d14cc1af32344241901c6a":{
      "scriptId":"u26"},
    "dc29560df5f245c2811875c9533988a2":{
      "scriptId":"u27"},
    "9d101934c6de44f6a6408bf77462ba06":{
      "scriptId":"u28"},
    "c32b3f0c2c034de8a774ffa775803bef":{
      "scriptId":"u29"},
    "98a1d68adce544d6a0f16bc71c16f0c7":{
      "scriptId":"u30"},
    "abbb98eed2414a5a9a859d123046a980":{
      "scriptId":"u31"},
    "a7f2b01198ef46dea6c04917643d12bb":{
      "scriptId":"u32"},
    "d13a9ada5bbd414f93e08f2a95436474":{
      "scriptId":"u33"},
    "6dd6e7c523d745ceaca3a12ef792542c":{
      "scriptId":"u34"},
    "02a6077ef92045cd9c15dd08b941e72f":{
      "scriptId":"u35"},
    "35e56f7813af4f2cb5aa2700b4e561c9":{
      "scriptId":"u36"},
    "8c41a0cf1ea6416f9de47b4a1150932a":{
      "scriptId":"u37"},
    "c62a4fe791594696a4c765f6d4b9446b":{
      "scriptId":"u38"},
    "1a6060b8ceca49f5ba97f22a2dc0d7e0":{
      "scriptId":"u39"},
    "3209bbd6dc784a149f415a5179a52a71":{
      "scriptId":"u40"},
    "e6a954599c434af7a34e37762b70e5f3":{
      "scriptId":"u41"},
    "068ae181c38d4703a4d27d37c0c6bdc0":{
      "scriptId":"u42"},
    "ca21f5cc33634c65af356371149d457a":{
      "scriptId":"u43"},
    "827db3e83c344734a82bde86ec98ced4":{
      "scriptId":"u44"},
    "45e08ea88020451ca8d748194707f4f8":{
      "scriptId":"u45"},
    "6d83d1053f13444eb262305f35c4475c":{
      "scriptId":"u46"},
    "cf1bd7a5e6e0498f802f5021bf93c191":{
      "scriptId":"u47"},
    "eb9207f0467d4841a544a78e2193b837":{
      "scriptId":"u48"}}});